import {
  ConfigInputs,
  GitLabCI,
  transform as transformToGitLab,
} from "@sleeyax/gitlab-ci-ts";
import {
  CIComponentGroupTemplate,
  GitLabJobWithSpec,
  IncludeWithSpec,
  GitHubWorkflow,
} from "./types";
import { stringify, parse } from "yaml";
import { $ } from "bun";
import { writeFile, rm, mkdir } from "fs/promises";
import { GitHubWorkflowReusable, GitHubJob } from "./github/github-actions";
import { transformInputsToGitHub } from "./transformer/input-transformers";

/**
 * GITHUB ACTIONS
 */

async function ExportGitHubActionsWorkflow(
  workflow: GitHubWorkflowReusable,
  filePath: string,
  header: string,
): Promise<void> {
  const yaml = stringify(workflow, {
    lineWidth: 0,
    aliasDuplicateObjects: false,
  });

  // Ensure output directory exists
  const dir = filePath.split("/").slice(0, -1).join("/");
  await mkdir(dir, { recursive: true });

  await writeFile(filePath, header + yaml);
  console.log(`Exported GitHub Actions workflow to ${filePath}`);
}

// OLD:
function convertToGitlabCI(pipeline: GitLabCI): any {
  const { jobs, ...rest } = pipeline;
  return {
    ...rest,
    // merge jobs into the root object
    ...jobs,
  };
}

async function transformToGitHubCompatibleYaml(
  pipeline: GitLabCI,
  filePath: string,
): Promise<void> {
  const { spec, ...rest } = pipeline; // drop specs as GitHub Actions doesn't support them
  const githubPipeline = convertToGitlabCI(rest);
  Object.values(githubPipeline).forEach((job: any) => {
    delete job.stage; // remove stage definitions as GitHub Actions doesn't support them
  });

  const yaml = stringify(githubPipeline, {
    lineWidth: 0,
    aliasDuplicateObjects: false,
  });
  await writeFile(filePath, yaml);
}
async function ExportGitHubActionsWorkflows(
  pipeline: GitLabCI,
  filePath: string,
  header = "# This file is automatically generated. Do not edit directly.\n\n",
): Promise<void> {
  const tmpYamlFile = "./github/tmp.yml";
  await transformToGitHubCompatibleYaml(pipeline, tmpYamlFile);

  await $`gh actions-importer dry-run gitlab --output-dir ./github/ --project dummy --namespace David-Development --source-file-path ${tmpYamlFile}`;

  const filePathDummy = `./github/David-Development/dummy/.github/workflows/dummy.yml`;
  const data: string = await Bun.file(filePathDummy).text();

  // console.log(data);
  const regex = /\$\[\[ inputs\.\S+ ]]/gm;

  // TODO!! what is this for??
  const replaced = data.replaceAll(regex, (match) => {
    console.log("Found match:", match);
    return match.replace("$[[", "${{").replace("]]", "}}");
  });
  // console.log(replaced);

  let githubWorkflow = parse(replaced);

  // remove properties that we do not use
  delete githubWorkflow.on;
  delete githubWorkflow.name;

  // set the workflow_call trigger with the merged inputs
  githubWorkflow = Object.assign(
    { on: { workflow_call: { inputs: pipeline.spec?.inputs } } },
    githubWorkflow,
  );

  // export the final GitHub Actions workflow
  const yaml = stringify(githubWorkflow, {
    lineWidth: 0,
    aliasDuplicateObjects: false,
  });
  await writeFile(filePath, header + yaml);

  console.log(`Exported GitHub Actions workflow to ${filePath}`);
}

/**
 * GITLAB CI
 */

async function ExportGitLabCI(
  pipeline: GitLabCI,
  filePath: string,
  header: string,
): Promise<void> {
  const yaml = transformToGitLab(pipeline);
  await writeFile(filePath, header + yaml);
  console.log(`Exported GitLab CI Template to ${filePath}`);
}

/**
 * OTHER
 */

async function GenerateMermaidDiagram(
  templates: CIComponentGroupTemplate,
): Promise<void> {
  const metaTemplates = Object.entries(templates).filter(
    ([templateName, template]) => template.length > 1,
  );
  const jobTemplates = Object.entries(templates).filter(
    ([templateName, template]) => template.length === 1,
  );

  const mermaid = `---
config:
  look: neo
  layout: elk
---
flowchart LR
  subgraph Jobs
  ${[...new Set(jobTemplates.map(([_, template]) => template.map((def) => templateSlug(def.name))))].join("\n  ")}
  end
${metaTemplates
      .map(([templateName, template]) => {
        const mapping = template
          .map((def) => `\n  ${templateName} --> ${templateSlug(def.name)}`)
          .join("");
        return `  ${mapping}`;
      })
      .join("\n")}`;
  console.log("Mermaid diagram of templates and their jobs:");
  console.log(mermaid);
}

/** Derive a safe snake_case prefix from a template name.
 *  "devguard:build_oci_image$[[ inputs.job_suffix ]]" → "build_oci_image"
 *  "jobB:$[[ inputs.other ]]"                        → "jobB"
 *  "jobA"                                             → "jobA"
 */
function templateSlug(name: string): string {
  const slug = name
    .replace(/^[^:]+:/, "") // drop "devguard:" / "namespace:" prefix
    .replace(/\$\[\[.*?\]\]/g, "") // drop $[[ … ]] interpolations
    .replace(/[^a-zA-Z0-9]+/g, "_") // non-alphanumeric → underscore
    .replace(/^_+|_+$/g, ""); // trim leading/trailing underscores

  // Fallback: if the whole useful part was inside an interpolation (e.g.
  // "jobB:$[[ inputs.other ]]"), use the segment before the first ":" or "$".
  if (!slug) {
    return name
      .split(/[:$]/)[0]
      .replace(/[^a-zA-Z0-9]+/g, "_")
      .replace(/^_+|_+$/g, "");
  }
  return slug;
}

/**
 * Detect conflicting input defaults across templates in a group.
 */
function checkForInputConflicts(
  templates: (GitHubWorkflow | GitLabJobWithSpec | IncludeWithSpec)[],
  ignoreKeys: string[] = [],
): void {
  // Collect every occurrence of each input key: key → [{templateIdx, serialised default}]
  const keyOccurrences = new Map<
    string,
    Array<{ idx: number; serialisedDefault: string }>
  >();
  for (let i = 0; i < templates.length; i++) {
    for (const [key, inputDef] of Object.entries(templates[i].inputs)) {
      if (ignoreKeys.includes(key)) continue;

      if (!keyOccurrences.has(key)) keyOccurrences.set(key, []);
      keyOccurrences.get(key)!.push({
        idx: i,
        serialisedDefault: JSON.stringify((inputDef as any)?.default),
      });
    }
  }

  // For each key: if any two templates disagree on the default → throw error
  for (const [key, occurrences] of keyOccurrences) {
    if (occurrences.length <= 1) continue;

    const first = occurrences[0].serialisedDefault;
    const allSame = occurrences.every((o) => o.serialisedDefault === first);
    if (!allSame) {
      const occurencesStr = occurrences
        .map(
          (o) =>
            `template "${templates[o.idx].name}" (default: ${o.serialisedDefault})`,
        )
        .join("\n  - ");
      throw new Error(
        `\nConflict detected for input "${key}": multiple templates define different defaults. Please resolve manually by:\n1. renaming the input keys\n2. overriding the keys to be unique across templates\n3. add override in Export function\n\nOccurrences:\n  - ${occurencesStr}\n\nOverriding Keys: ${ignoreKeys.join(", ")}`,
      );
    }
  }
}

export async function ExportCIComponents(
  templates: CIComponentGroupTemplate,
  header: string,
  inputOverrides: { [key: string]: ConfigInputs } = {},
): Promise<void> {
  GenerateMermaidDiagram(templates);

  // Ensure output directories exist
  await mkdir("./github/", { recursive: true });
  await mkdir("./templates/", { recursive: true });
  await mkdir("./.github/workflows/", { recursive: true });

  for (const [templateName, template] of Object.entries(templates)) {
    // Check for conflicting input defaults before merging
    checkForInputConflicts(
      template,
      Object.keys(inputOverrides[templateName] ?? {}),
    );

    const mergedInputs = Object.assign(
      {},
      ...template.map((t) => t.inputs),
      inputOverrides[templateName] ?? {},
    );

    // find all entries with Jobs
    const jobDefs = template.filter(
      (t): t is GitLabJobWithSpec | GitHubWorkflow => "job" in t,
    );

    const isWorkflowJob = (job: any): job is GitHubJob =>
      typeof job === "object" &&
      job !== null &&
      ("toGitHub" in job || "runs-on" in job); // TODO.. rework this logic once Tims PoC is fully removed

    // Separate WorkflowJob instances from legacy (GitLab only) jobs
    const githubJobs = jobDefs.filter((def): def is GitHubWorkflow =>
      isWorkflowJob(def.job),
    );
    const gitlabJobs = jobDefs.filter(
      (def): def is GitLabJobWithSpec => !isWorkflowJob(def.job),
    );

    // ─── GITLAB CI EXPORT ───────────────────────────────────

    const pipeline: GitLabCI = {
      spec: {
        inputs: mergedInputs,
      },
      jobs: gitlabJobs.reduce(
        (acc, def) => ({ ...acc, [def.name]: def.job }),
        {},
      ),
      include: template
        .filter((t): t is IncludeWithSpec => "include" in t)
        .reduce(
          (acc, curr) => [...acc, curr.include],
          [] as IncludeWithSpec["include"][],
        ),
    };

    const filenameGitLab = `./templates/${templateName}.yml`;
    await ExportGitLabCI(pipeline, filenameGitLab, header);

    // ─── GITHUB ACTIONS EXPORT ──────────────────────────────
    // Only export if there are WorkflowJob instances
    if (githubJobs.length > 0) {
      const githubWorkflow: GitHubWorkflowReusable = {
        on: {
          workflow_call: {
            inputs: transformInputsToGitHub(mergedInputs),
            secrets: githubJobs
              .filter((job) => job.secrets)
              .reduce((acc, def) => ({ ...acc, ...def.secrets }), {}),
          },
        },
        jobs: githubJobs.reduce(
          (acc, def) => ({ ...acc, [templateSlug(def.name)]: def.job }),
          {},
        ),
      };

      const filenameGitHub = `./.github/workflows/${templateName}.yml`;
      await ExportGitHubActionsWorkflow(githubWorkflow, filenameGitHub, header);
      console.log(
        `Exported template "${templateName}" to GitHub Actions: ${filenameGitHub}`,
      );

      // Marked for deletion...
      // const filenameGitHub2 = `./.github/workflows/${templateName}-2.yml`;
      // await ExportGitHubActionsWorkflows(pipeline, filenameGitHub2, header);
      // console.log(`Exported template "${templateName}" to GitHub Actions: ${filenameGitHub2}`);
    }
  }
  // await rm("./github/", { recursive: true, force: true });
}
