# This is a test configuration for the DevGuard scanner components.
# The results can be viewed on the DevGuard dashboard at: 
# https://main.devguard.org/l3montree-cybersecurity/projects/devguard-pipeline/assets/devguard-pipeline

stages:
- build
- test
- release


include:
- component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/sca@$CI_COMMIT_SHA
  inputs:
    asset_name: "$DEVGUARD_ASSET_NAME"
    token: "$DEVGUARD_TOKEN"
    #You can change this to the desired stage. Make sure it matches one of your defined stages.
    scan_stage: test

- component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/container-scanning@$CI_COMMIT_SHA
  inputs:
    asset_name: "$DEVGUARD_ASSET_NAME"
    token: "$DEVGUARD_TOKEN"
    #You can change these to the desired stages. Make sure they match one of your defined stages.
    scan_stage: test
    build_stage: "build"
- component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/deploy@$CI_COMMIT_SHA
  inputs:
    #You can change this to the desired stage. Make sure it matches one of your defined stages.
    deploy_stage: "deploy"

create-release:
  stage: release
  dependencies:
  - devguard-software-composition-analysis
  - devguard-container-scanning
  image: registry.gitlab.com/gitlab-org/release-cli:v0.18.0@sha256:696013aea0f2a20482800ce3a77341f840d7c7ec17bd78bd555e0bd6c00e4f11
  script: echo "Creating release $CI_COMMIT_TAG"
  rules:
  - if: $CI_COMMIT_TAG
  release:
    tag_name: $CI_COMMIT_TAG
    description: "Release $CI_COMMIT_TAG of components in $CI_PROJECT_PATH"
