import { ExportCIComponents, CIComponentGroupTemplate } from "@l3montree/programmatic-ci-components";
import { SourceProvenanceTemplate } from "./templates/source-provenance-attestation";
import { AttestJobInputs, AttestTemplate } from "./templates/attest";
import { SecretScanningJobInputs, SecretScanningTemplate } from "./templates/secret-scanning";
import { SASTJobInputs, StaticApplicationSecurityTestingTemplate } from "./templates/static-application-security-testing";
import * as fs from "node:fs";
import { IaCJobInputs, InfrastructureAsCodeScanningTemplate } from "./templates/infrastructure-as-code-scanning";
import { SCAJobInputs, SoftwareCompositionAnalysisTemplate } from "./templates/software-composition-analysis";
import { GenerateTagJobInputs, GenerateTagTemplate } from "./templates/generate-tag";
import { BuildOciImageJobInputs, BuildOciImageTemplate } from "./templates/build-oci-image";
import { ContainerScanningJobInputs, ContainerScanningTemplate } from "./templates/container-scanning";
import { PushOciImageJobInputs, PushOciImageTemplate } from "./templates/push-oci-image";
import { SignOciImageJobInputs, SignOciImageTemplate } from "./templates/sign-oci-image";
import { BuildNixExtractScannerTemplate, BuildNixGenerateTagTemplate, BuildNixTemplate } from "./templates/build-nix";
import { CreateManifestMultiArchTemplate } from "./templates/create-manifest-multi-arch";



const fullGenerateTag = GenerateTagTemplate({ stage: "generate-tag", git_strategy: GenerateTagJobInputs.git_strategy.default });
const fullBuildOciImage = BuildOciImageTemplate({ stage: "build", git_strategy: BuildOciImageJobInputs.git_strategy.default, image: BuildOciImageJobInputs.image.default, image_tag: "$IMAGE_TAG", needs: [ fullGenerateTag.name ], dependencies: [ fullGenerateTag.name ] });
const fullContrainerScannig = ContainerScanningTemplate({ stage: "test", git_strategy: ContainerScanningJobInputs.git_strategy.default, image_tag: "$IMAGE_TAG", needs: [ fullBuildOciImage.name ], dependencies: [ fullBuildOciImage.name ] });
const fullPushOCIImage = PushOciImageTemplate({ stage: "deploy", image: PushOciImageJobInputs.image.default, image_tag: "$IMAGE_TAG", needs: [ fullContrainerScannig.name ], dependencies: [ fullContrainerScannig.name ] });


const templates: CIComponentGroupTemplate = {
    "source-provenance-attestation": [
        SourceProvenanceTemplate({}),
    ],
    "attest": [
        AttestTemplate({}),
    ],
    "secret-scanning": [
        SecretScanningTemplate({}),
    ],
    "static-application-security-testing": [
        StaticApplicationSecurityTestingTemplate({})
    ],
    "infrastructure-as-code-scanning": [
        InfrastructureAsCodeScanningTemplate({}),
    ],
    "software-composition-analysis": [
        SoftwareCompositionAnalysisTemplate({}),
    ],
    "generate-tag": [
        GenerateTagTemplate({}),
    ],
    "build-oci-image": [
        BuildOciImageTemplate({}),
    ],
    "container-scanning": [
        ContainerScanningTemplate({}),
    ],
    "push-oci-image": [
        PushOciImageTemplate({}),
    ],
    "sign-oci-image": [
        SignOciImageTemplate({}),
    ],
    "build-nix": [
        BuildNixExtractScannerTemplate({}),
        BuildNixGenerateTagTemplate({}),
        BuildNixTemplate({}),
    ],
    "create-manifest-multi-arch": [
        CreateManifestMultiArchTemplate({}),
    ],
    "full": [
        SourceProvenanceTemplate({}),
        AttestTemplate({ stage: AttestJobInputs.stage.default }),
        SecretScanningTemplate({ git_strategy: SecretScanningJobInputs.git_strategy.default }),
        StaticApplicationSecurityTestingTemplate({ git_strategy: SASTJobInputs.git_strategy.default }),
        InfrastructureAsCodeScanningTemplate({ git_strategy: IaCJobInputs.git_strategy.default }),
        SoftwareCompositionAnalysisTemplate({ git_strategy: SCAJobInputs.git_strategy.default }),
        fullGenerateTag,
        fullBuildOciImage,
        fullContrainerScannig,
        fullPushOCIImage,
        SignOciImageTemplate({ stage: "deploy", git_strategy: SignOciImageJobInputs.git_strategy.default, image: SignOciImageJobInputs.image.default,  needs: [ fullPushOCIImage.name ], dependencies: [ fullPushOCIImage.name ] }),
    ]
}

const header = `# Copyright 2025 l3montree GmbH.
# SPDX-License-Identifier: AGPL-3.0

# This file is automatically generated. Do not edit directly.
`

await ExportCIComponents(templates, header, {
    full: {
        // needs/dependencies are hardcoded in job bodies above (not inputs),
        // so remove their now-orphaned input keys from the merged spec.
        excludeInputs: ["needs", "dependencies"],
    },
});


// copy files over using fs
for (const templateName of Object.keys(templates)) {
    fs.copyFileSync(`../programmatic-ci-components-test-gitlab/templates/${templateName}.yml`, `./templates/${templateName}.yml`)
}

// console.log("Finished");
