FROM ghcr.io/l3montree-dev/devguard/scanner:v0.19.2@sha256:44d6017fefe82849397b63b3827ac3793476f295b1dc9968f70db6f9ac052301 AS devguard-scanner
# https://github.com/l3montree-dev/devguard/blob/main/Dockerfile.scanner
# See the Scanner Dockerfile for the used versions of crane and devguard-scanner

# checkov:skip=CKV_DOCKER_2
# checkov:skip=CKV_DOCKER_3

# https://github.com/osscontainertools/kaniko
FROM ghcr.io/osscontainertools/kaniko:v1.26.0-debug@sha256:79e919821131a5d7846992de4c2fdb64bb1aa298a6cfd772a8740cda8648e545 AS kaniko-executor

FROM alpine:3.22.2@sha256:4b7ce07002c69e8f3d704a9c5d6fd3053be500b7f1c69fc0d80990c2ad8dd412

WORKDIR /

COPY --from=devguard-scanner /usr/local/bin/crane .
COPY --from=devguard-scanner /usr/local/bin/devguard-scanner .

COPY --from=kaniko-executor /kaniko /kaniko
COPY --from=kaniko-executor /workspace /workspace

RUN apk update && apk add --no-cache git dbus dbus-x11 gnome-keyring busybox jq

WORKDIR /workspace

ENTRYPOINT ["/kaniko/executor"]