FROM ghcr.io/l3montree-dev/devguard/scanner:main-3ff663b9-1756455617@sha256:0088d78a7204605a4831e0079f12cf33429e0753bc869b3345746754c123a76a AS devguard-scanner
# https://github.com/l3montree-dev/devguard/blob/main/Dockerfile.scanner
# See the Scanner Dockerfile for the used versions of crane and devguard-scanner

FROM registry.gitlab.com/l3montree/devguard/kaniko-project/executor:v1.24.0-debug@sha256:0acd73a81eb8a1a2f69cd431d0834bb53dce221f8b996f2d28a62a5e84abfdc9

# checkov:skip=CKV_DOCKER_2
# checkov:skip=CKV_DOCKER_3

WORKDIR /

COPY --from=devguard-scanner /usr/local/bin/crane .
COPY --from=devguard-scanner /usr/local/bin/devguard-scanner .

WORKDIR /workspace
