FROM ghcr.io/l3montree-dev/devguard/scanner:main-b4fe2821-1756465014@sha256:29fbee19625201e211011cdf34089f983b873d035a16813333bcaa42785c8dfd AS devguard-scanner
# https://github.com/l3montree-dev/devguard/blob/main/Dockerfile.scanner
# See the Scanner Dockerfile for the used versions of crane and devguard-scanner

# checkov:skip=CKV_DOCKER_2
# checkov:skip=CKV_DOCKER_3

FROM registry.gitlab.com/l3montree/devguard/kaniko-project/executor:v1.24.0-debug@sha256:0acd73a81eb8a1a2f69cd431d0834bb53dce221f8b996f2d28a62a5e84abfdc9 AS kaniko-executor

FROM alpine:3.22.1@sha256:4bcff63911fcb4448bd4fdacec207030997caf25e9bea4045fa6c8c44de311d1

WORKDIR /

COPY --from=devguard-scanner /usr/local/bin/crane .
COPY --from=devguard-scanner /usr/local/bin/devguard-scanner .

COPY --from=kaniko-executor /kaniko /kaniko
COPY --from=kaniko-executor /workspace /workspace

RUN apk update && apk add --no-cache git dbus dbus-x11 gnome-keyring

WORKDIR /workspace

ENTRYPOINT ["/kaniko/executor"]