variables:
  GIT_STRATEGY: clone

# generate an SBOM using trivy?
# use whatever scanner you like, this is just an example
generate-sbom:
  stage: build
  image:
    name: docker.io/aquasec/trivy:latest
    entrypoint: [""]
  script:
    - trivy fs . --format cyclonedx --output sbom.json
  artifacts:
    paths:
      - sbom.json
    expire_in: 1 week

# upload the SBOM to DevGuard
include:
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/dependency-risk-identification@$CI_COMMIT_SHA
    inputs:
      sbom_file: "sbom.json"
      devguard_asset_name: "$DEVGUARD_ASSET_NAME"
      devguard_token: "$DEVGUARD_TOKEN"
      devguard_api_url: "https://api.main.devguard.org"
      needs:
        - generate-sbom
      dependencies:
        - generate-sbom
