variables:
  GIT_STRATEGY: clone

include:
  - component: $CI_SERVER_FQDN/$CI_PROJECT_PATH/dependency-risk-identification@$CI_COMMIT_SHA
    inputs:
      sbom_file: "sbom-in-repo.json"
      devguard_asset_name: "$DEVGUARD_ASSET_NAME"
      devguard_token: "$DEVGUARD_TOKEN"
      devguard_api_url: "https://api.main.devguard.org"
