spec:
  inputs:
    build_stage:
      default: "build"
      description: "The stage where the image is built and tagged"
    build_args:
      default: "--context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile"
      description: "The build arguments to pass to the Kaniko build command"
    push_image:
      default: "false"
      description: "It is preferred, that the image gets only pushed to the registry after scanning. Todo so, it gets passed to the container scanning as artifact. Nevertheless, some gitlab instances have a small maximum artifact upload size. If this applies to you, set this flag to true. This wont upload it as artifact but pushes it directly into the registry."
    artifact_name:
      description: "The name of the artifact that contains the image. This is used to pass the image to the container scanning job."  
    token:
      description: "The token to authenticate against the DevGuard API"
    api_url:
      default: "https://api.main.devguard.org"
      description: "The DevGuard API URL"
    asset_name:
      description: "The name of the asset"
    runner_tags:
      default: ""
      description: "The runner tag to use for the job"  
---
variables:
  GIT_STRATEGY: clone
  

# OCI Build: Uses Kaniko to build Docker images securely without requiring privileged access (docker in docker needs privileged access). The artifacts are not pushed to the registry until they have undergone security scanning to ensure vulnerabilities are addressed before deployment - therefore they are stored as artifacts rather than pushed to the registry.
devguard:build-image:$[[ inputs.artifact_name ]]:
  stage: "$[[ inputs.build_stage ]]"
  tags:
    - $[[ inputs.runner_tags ]]
  needs: []
  dependencies: []
  image:
    name: registry.gitlab.com/l3montree/devguard/kaniko-crane@sha256:034bde4e093de194f142c813f00bbee7e78083f2f08d582875b6f969ee32f0db # gitlab ci always needs a shell in the container it executes... i would have preferred the non-debug version
    entrypoint: [""]
  before_script:
    - echo "Uses Kaniko to build Docker images securely without requiring privileged access (docker in docker needs privileged access).\n The artifacts are not pushed to the registry until they have undergone security scanning to ensure vulnerabilities are addressed before deployment - therefore they are stored as artifacts rather than pushed to the registry."
    - |
        /devguard-scanner intoto start --step=build --ignore=image-digest.txt --ignore=image-tag.txt --token="$[[ inputs.token ]]" --apiUrl="$[[ inputs.api_url ]]" --assetName="$[[ inputs.asset_name ]]" --supplyChainId="${CI_COMMIT_SHA}"
    - |
      if [ -n "$CI_COMMIT_TAG" ]; then
        # Set IMAGE_TAG if the pipeline was triggered by a tag
        echo "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" > image-tag.txt
      else
        # Set IMAGE_TAG if the pipeline was triggered by a push to main
        branch=$(echo $CI_COMMIT_REF_NAME | sed 's/\//-/g')
        sha=${CI_COMMIT_SHORT_SHA}
        ts=$(date +%s)
        echo "$CI_REGISTRY_IMAGE:${branch}-${sha}-${ts}" > image-tag.txt
      fi
  script:
    - /crane auth login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - /kaniko/executor $[[ inputs.build_args ]] --ignore-path=/devguard-scanner --ignore-path=/crane --destination $(cat image-tag.txt) $([[ "$[[ inputs.push_image ]]" == "false" ]] && echo "--no-push --tarPath image.tar")
    # install crane
    - /crane digest $([[ "$[[ inputs.push_image ]]" == "false" ]] && echo "--tarball=image.tar" || cat image-tag.txt) > image-digest.txt

    - |
        echo "Running DevGuard Intoto Build...stopping..."
        /devguard-scanner intoto stop --step=build --products=image-digest.txt --products=image-tag.txt --token="$[[ inputs.token ]]" --apiUrl="$[[ inputs.api_url ]]" --assetName="$[[ inputs.asset_name ]]" --supplyChainId="${CI_COMMIT_SHA}" --generateSlsaProvenance
  artifacts:
    name: "$[[ inputs.artifact_name ]]"
    paths:
      - image.tar
      - image-tag.txt
      - image-digest.txt
      - build.provenance.json
    when: on_success
