spec:
  inputs:
    build_stage:
      default: 'build'
      description: 'The stage where the image is built and tagged'
    build_args:
      default: '--context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile'
      description: 'The build arguments to pass to the Kaniko build command'
---
# OCI Build: Uses Kaniko to build Docker images securely without requiring privileged access (docker in docker needs privileged access). The artifacts are not pushed to the registry until they have undergone security scanning to ensure vulnerabilities are addressed before deployment - therefore they are stored as artifacts rather than pushed to the registry.
devguard:build-image:
  stage: "$[[ inputs.build_stage ]]"
  needs: []
  dependencies: []
  image:
    name: registry.gitlab.com/l3montree/devguard/kaniko-crane@sha256:f2a8edc860181ffe23200fece4689e9338a3c2d98db464d0beb28da023aad14b # gitlab ci always needs a shell in the container it executes... i would have preferred the non-debug version
    entrypoint: [ "" ]
  before_script:
  - echo "Uses Kaniko to build Docker images securely without requiring privileged access (docker in docker needs privileged access).\n The artifacts are not pushed to the registry until they have undergone security scanning to ensure vulnerabilities are addressed before deployment - therefore they are stored as artifacts rather than pushed to the registry."
  - |
    if [ -n "$CI_COMMIT_TAG" ]; then
      # Set IMAGE_TAG if the pipeline was triggered by a tag
      echo "$CI_REGISTRY_IMAGE:$CI_COMMIT_TAG" > image-tag.txt
    else
      # Set IMAGE_TAG if the pipeline was triggered by a push to main
      branch=$(echo $CI_COMMIT_REF_NAME | sed 's/\//-/g')
      sha=${CI_COMMIT_SHORT_SHA}
      ts=$(date +%s)
      echo "$CI_REGISTRY_IMAGE:${branch}-${sha}-${ts}" > image-tag.txt
    fi
  script:
  - /kaniko/executor --no-push $[[ inputs.build_args ]] --destination $(cat image-tag.txt) --tarPath image.tar
  # install crane 
  - /crane digest --tarball=image.tar > image-digest.txt

  artifacts:
    paths:
    - image.tar
    - image-tag.txt
    - image-digest.txt
    when: on_success

  only:
  - main
  - devguard-setup
