import { AttestJobInputs, AttestTemplate } from "./templates/attest";
import { BuildNixExtractScannerTemplate, BuildNixGenerateTagTemplate, BuildNixTemplate } from "./templates/build-nix";
import { BuildOciImageJobInputs, BuildOciImageTemplate } from "./templates/build-oci-image";
import { ContainerScanningJobInputs, ContainerScanningTemplate } from "./templates/container-scanning";
import { GenerateTagJobInputs, GenerateTagTemplate } from "./templates/generate-tag";
import { IaCJobInputs, InfrastructureAsCodeScanningTemplate } from "./templates/infrastructure-as-code-scanning";
import { PushOciImageJobInputs, PushOciImageTemplate } from "./templates/push-oci-image";
import { SignOciImageJobInputs, SignOciImageTemplate } from "./templates/sign-oci-image";
import { SCAJobInputs, SoftwareCompositionAnalysisTemplate } from "./templates/software-composition-analysis";
import {
  SASTJobInputs,
  StaticApplicationSecurityTestingTemplate,
} from "./templates/static-application-security-testing";
import { BuildNixMultiArchBuildImageTemplate, BuildNixMultiArchCreateManifestTemplate } from "./templates/build-nix-multiarch";
import { CIComponentGroupTemplateGitHub, CIComponentGroupTemplateGitLab, GitHubOrchestratorWorkflow } from "./lib/types";
import { ExportCIComponentsGitHub, ExportCIComponentsGitLab, ExportGitHubOrchestratorWorkflows } from "./lib/utils";
import { BuildOciImageWDockerTemplate } from "./templates/build-oci-image-w-docker";
import { CreateManifestMultiArchTemplate } from "./templates/create-manifest-multi-arch";
import { DiscoverBaseimageAttestationsTemplate } from "./templates/discover-baseimage-attestations";
import { Inputs } from "./templates/inputs";
import { ReleaseTemplate } from "./templates/release";
import { SarifUploadTemplate } from "./templates/sarif-upload";
import { SbomUploadTemplate } from "./templates/sbom-upload";
import { SourceProvenanceTemplate } from "./templates/source-provenance-attestation";
import { VexUploadTemplate } from "./templates/vex-upload";
import {
  SecretScanningTemplateGitHub,
  SecretScanningTemplateGitLab,
  SecretScanningJobInputsGitLab,
} from "./templates/secret-scanning";
import { BuildOciImageTemplateGitHub } from "./templates/build-oci-image";
import { ContainerScanningTemplateGitHub } from "./templates/container-scanning";
import { SoftwareCompositionAnalysisTemplateGitHub } from "./templates/software-composition-analysis";
import { StaticApplicationSecurityTestingTemplateGitHub } from "./templates/static-application-security-testing";
import { InfrastructureAsCodeScanningTemplateGitHub } from "./templates/infrastructure-as-code-scanning";
import { DeployTemplateGitHub, DeployTemplateGitLab } from "./templates/deploy";
import { SignTemplateGitHub } from "./templates/sign-oci-image";
import { AttestTemplateGitHub } from "./templates/attest";
import { GenerateTagTemplateGitHub } from "./templates/generate-tag";
import { PushOciImageTemplateGitHub } from "./templates/push-oci-image";
import { SbomUploadTemplateGitHub } from "./templates/sbom-upload";
import { VexUploadTemplateGitHub } from "./templates/vex-upload";
import { ReleaseTemplateGitHub } from "./templates/release";
import { BuildOciImageWDockerTemplateGitHub } from "./templates/build-oci-image-w-docker";
import { CreateManifestMultiArchTemplateGitHub } from "./templates/create-manifest-multi-arch";
import { DiscoverBaseimageAttestationsTemplateGitHub } from "./templates/discover-baseimage-attestations";
import { SarifUploadTemplateGitHub } from "./templates/sarif-upload";
import { BuildNixMultiArchBuildImageTemplateGitHub, BuildNixMultiArchCreateManifestTemplateGitHub } from "./templates/build-nix-multiarch";
import { BuildNixTemplateGitHub } from "./templates/build-nix";
import { ZizmorScanningTemplateGitHub } from "./templates/zizmor-scanning";

// const fileHeader = `# Copyright 2025-${new Date().getFullYear()} l3montree GmbH.
const fileHeader = `# Copyright 2025 l3montree GmbH.
# SPDX-License-Identifier: AGPL-3.0

# This file is automatically generated. Do not edit directly.
`;

// ── full ──────────────────────────────────────────────────────────────────────
const fullGenerateTag = GenerateTagTemplate({
  stage: "oci-image",
  git_strategy: GenerateTagJobInputs.git_strategy.default,
});
const fullBuildOciImage = BuildOciImageTemplate({
  stage: "oci-image",
  git_strategy: BuildOciImageJobInputs.git_strategy.default,
  image: BuildOciImageJobInputs.image.default,
  image_tag: "$IMAGE_TAG",
  needs: [fullGenerateTag.name],
  dependencies: [fullGenerateTag.name],
  push_image: "$[[ inputs.small_artifact_registry ]]",
});
const fullContrainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: ContainerScanningJobInputs.git_strategy.default,
  image_tag: "",
  devguard_artifact_name: "$ARTIFACT_NAME",
  needs: [fullGenerateTag.name, fullBuildOciImage.name],
  dependencies: [fullGenerateTag.name, fullBuildOciImage.name],
});
const fullPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  image: PushOciImageJobInputs.image.default,
  image_tag: "$IMAGE_TAG",
  needs: [fullGenerateTag.name, fullBuildOciImage.name, fullContrainerScanning.name],
  dependencies: [fullGenerateTag.name, fullBuildOciImage.name, fullContrainerScanning.name],
  disable_job: "$[[ inputs.small_artifact_registry ]]",
});
const fullSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: SignOciImageJobInputs.git_strategy.default,
  image: "$IMAGE_TAG",
  needs: [fullGenerateTag.name, fullBuildOciImage.name, { job: fullPushOciImage.name, optional: true }],
  dependencies: [fullGenerateTag.name, fullBuildOciImage.name, fullPushOciImage.name],
});
const fullSourceProvenanceAttestation = SourceProvenanceTemplate({
  stage: AttestJobInputs.stage.default,
});
const fullAttest = AttestTemplate({
  stage: AttestJobInputs.stage.default,
  devguard_artifact_name: "$ARTIFACT_NAME",
  image: "$IMAGE_TAG",
  needs: [
    fullGenerateTag.name,
    fullSignOciImage.name,
    fullBuildOciImage.name,
    { job: "source-provenance-artifacts", optional: true },
  ],
  attestations: [
    {
      source:
        "$[[ inputs.devguard_api_url ]]/api/v1/organizations/$[[ inputs.devguard_asset_name ]]/refs/COMMIT_REF/artifacts/ARTIFACT_NAME/sbom.json/",
      predicate_type: "https://cyclonedx.org/bom",
    },
    {
      source:
        "$[[ inputs.devguard_api_url ]]/api/v1/organizations/$[[ inputs.devguard_asset_name ]]/refs/COMMIT_REF/artifacts/ARTIFACT_NAME/vex.json/",
      predicate_type: "https://cyclonedx.org/vex",
    },
    {
      source:
        "$[[ inputs.devguard_api_url ]]/api/v1/organizations/$[[ inputs.devguard_asset_name ]]/refs/COMMIT_REF/sarif.json/",
      predicate_type: "https://www.schemastore.org/schemas/json/sarif-2.1.0.json",
    },
    {
      source: "build.provenance.json",
      predicate_type: "https://slsa.dev/provenance/v1",
    },
    {
      source: "artifacts/attestation-report.json",
      predicate_type:
        "https://gitlab.opencode.de/open-code/badgebackend/source-provenance-attestation-service/-/raw/main/schema/source-provenance-schema-1.0.1.json",
    },
  ],
});

// ── container-lifecycle ───────────────────────────────────────────────────────
const clGenerateTag = GenerateTagTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
});
const clBuildOciImage = BuildOciImageTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clGenerateTag.name],
  dependencies: [clGenerateTag.name],
});
const clContainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image_tar_path: "image.tar",
  needs: [clBuildOciImage.name],
  dependencies: [clBuildOciImage.name],
});
const clPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clGenerateTag.name, clBuildOciImage.name, clContainerScanning.name],
  dependencies: [clGenerateTag.name, clBuildOciImage.name, clContainerScanning.name],
});
const clSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [clGenerateTag.name, clPushOciImage.name],
  dependencies: [clGenerateTag.name, clPushOciImage.name],
});
const clAttest = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  needs: [clGenerateTag.name, clPushOciImage.name, clBuildOciImage.name, clContainerScanning.name],
});

// ── container-lifecycle-nix ───────────────────────────────────────────────────
const clnExtractScanner = BuildNixExtractScannerTemplate({});
const clnGenerateTag = BuildNixGenerateTagTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
});
const clnBuildOciImage = BuildNixTemplate({
  stage: "oci-image",
  image: "image.tar",
  needs: [clnGenerateTag.name],
  dependencies: [clnGenerateTag.name],
});
const clnContainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image_tar_path: "image.tar",
  needs: [clnGenerateTag.name, clnBuildOciImage.name],
  dependencies: [clnGenerateTag.name, clnBuildOciImage.name],
});
const clnPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clnGenerateTag.name, clnBuildOciImage.name, clnContainerScanning.name],
  dependencies: [clnGenerateTag.name, clnBuildOciImage.name, clnContainerScanning.name],
});
const clnSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [clnGenerateTag.name, clnPushOciImage.name],
  dependencies: [clnGenerateTag.name, clnPushOciImage.name],
});
const clnAttest = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  needs: [clnGenerateTag.name, clnPushOciImage.name, clnBuildOciImage.name, clnContainerScanning.name],
});

// ── push-and-attest ───────────────────────────────────────────────────────────
const paGenerateTag = GenerateTagTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
});
const paPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [paGenerateTag.name, "$[[ inputs.build_job_name ]]"],
  dependencies: [paGenerateTag.name, "$[[ inputs.build_job_name ]]"],
});
const paSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [paGenerateTag.name, paPushOciImage.name],
  dependencies: [paGenerateTag.name, paPushOciImage.name],
});
const paAttest = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  needs: [paGenerateTag.name, "$[[ inputs.build_job_name ]]", paPushOciImage.name],
});

// ── container-scanning-and-attest ─────────────────────────────────────────────
const csaGenerateTag = GenerateTagTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
});
const csaContainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  needs: [csaGenerateTag.name, "$[[ inputs.build_job_name ]]"],
  dependencies: [csaGenerateTag.name, "$[[ inputs.build_job_name ]]"],
});
const csaPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [csaGenerateTag.name, csaContainerScanning.name, "$[[ inputs.build_job_name ]]"],
  dependencies: [csaGenerateTag.name, csaContainerScanning.name, "$[[ inputs.build_job_name ]]"],
});
const csaSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [csaGenerateTag.name, csaPushOciImage.name],
  dependencies: [csaGenerateTag.name, csaPushOciImage.name],
});
const csaAttest = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  needs: [csaGenerateTag.name, "$[[ inputs.build_job_name ]]", csaContainerScanning.name, csaPushOciImage.name],
});

// ── container-lifecycle-with-base-image-inspection ────────────────────────────
const clbiDiscoverAttestations = DiscoverBaseimageAttestationsTemplate({
  stage: "oci-image",
  allow_failure: true,
});
const clbiGenerateTag = GenerateTagTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
});
const clbiBuildOciImage = BuildOciImageTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clbiGenerateTag.name],
  dependencies: [clbiGenerateTag.name],
});
const clbiContainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image_tar_path: "image.tar",
  needs: [clbiBuildOciImage.name],
  dependencies: [clbiBuildOciImage.name],
});
const clbiPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clbiGenerateTag.name, clbiBuildOciImage.name, clbiContainerScanning.name],
  dependencies: [clbiGenerateTag.name, clbiBuildOciImage.name, clbiContainerScanning.name],
});
const clbiSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [clbiGenerateTag.name, clbiPushOciImage.name],
  dependencies: [clbiGenerateTag.name, clbiPushOciImage.name],
});
const clbiAttest = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  needs: [clbiGenerateTag.name, clbiPushOciImage.name, clbiBuildOciImage.name, clbiContainerScanning.name],
});
// sbom/vex upload depend on discover_baseimage_attestations; file paths use $[[ inputs.output ]] (added via inputOverrides)
const clbiSbomUpload = SbomUploadTemplate({
  stage: "attestation",
  allow_failure: true,
  git_strategy: "none",
  sbom_file: "$[[ inputs.output ]]/attestation-bom.json",
  devguard_origin: "BASE_IMAGE_SBOM",
  needs: [clbiDiscoverAttestations.name],
  dependencies: [clbiDiscoverAttestations.name],
});
const clbiVexUpload = VexUploadTemplate({
  stage: "attestation",
  allow_failure: true,
  git_strategy: "none",
  vex_file: "$[[ inputs.output ]]/attestation-vex.json",
  devguard_origin: "BASE_IMAGE_VEX",
  needs: [clbiDiscoverAttestations.name, clbiSbomUpload.name],
  dependencies: [clbiDiscoverAttestations.name, clbiSbomUpload.name],
});

const templates: CIComponentGroupTemplateGitLab = {
  // ── Individual job templates ──────────────────────────────────────────────
  // "source-provenance-attestation": [
  //     SourceProvenanceTemplate({}),
  // ],

  attest: [AttestTemplate({})],
  "secret-scanning": [SecretScanningTemplateGitLab({})],
  "static-application-security-testing": [StaticApplicationSecurityTestingTemplate({})],
  "infrastructure-as-code-scanning": [InfrastructureAsCodeScanningTemplate({})],
  "software-composition-analysis": [SoftwareCompositionAnalysisTemplate({})],
  "generate-tag": [GenerateTagTemplate({})],
  "build-oci-image": [BuildOciImageTemplate({})],
  "build-oci-image-w-docker": [BuildOciImageWDockerTemplate({})],
  "container-scanning": [ContainerScanningTemplate({})],
  "push-oci-image": [PushOciImageTemplate({})],
  "sign-oci-image": [SignOciImageTemplate({})],
  "create-manifest-multi-arch": [CreateManifestMultiArchTemplate({})],
  "sarif-upload": [SarifUploadTemplate({})],
  "sbom-upload": [SbomUploadTemplate({})],
  "vex-upload": [VexUploadTemplate({})],
  "discover-baseimage-attestations": [DiscoverBaseimageAttestationsTemplate({})],
  release: [ReleaseTemplate({})],
  deploy: [DeployTemplateGitLab({})],

  // ── Orchestration templates ───────────────────────────────────────────────
  full: [
    fullSourceProvenanceAttestation,
    SecretScanningTemplateGitLab({
      git_strategy: SecretScanningJobInputsGitLab.git_strategy.default,
    }),
    StaticApplicationSecurityTestingTemplate({
      git_strategy: SASTJobInputs.git_strategy.default,
    }),
    InfrastructureAsCodeScanningTemplate({
      git_strategy: IaCJobInputs.git_strategy.default,
    }),
    SoftwareCompositionAnalysisTemplate({
      git_strategy: SCAJobInputs.git_strategy.default,
    }),
    fullGenerateTag,
    fullBuildOciImage,
    fullContrainerScanning,
    fullPushOciImage,
    fullSignOciImage,
    fullAttest,
  ],
  "container-lifecycle": [
    clGenerateTag,
    clBuildOciImage,
    clContainerScanning,
    clPushOciImage,
    clSignOciImage,
    clAttest,
  ],
  "container-lifecycle-nix": [
    clnExtractScanner,
    clnGenerateTag,
    clnBuildOciImage,
    clnContainerScanning,
    clnPushOciImage,
    clnSignOciImage,
    clnAttest,
  ],
  "push-and-attest": [paGenerateTag, paPushOciImage, paSignOciImage, paAttest],
  "container-scanning-and-attest": [
    csaGenerateTag,
    csaContainerScanning,
    csaPushOciImage,
    csaSignOciImage,
    csaAttest,
  ],
  "container-lifecycle-with-base-image-inspection": [
    clbiDiscoverAttestations,
    clbiGenerateTag,
    clbiBuildOciImage,
    clbiContainerScanning,
    clbiPushOciImage,
    clbiSignOciImage,
    clbiAttest,
    clbiSbomUpload,
    clbiVexUpload,
  ],
  "build-nix": [
    BuildNixExtractScannerTemplate({}),
    BuildNixGenerateTagTemplate({}),
    BuildNixTemplate({}),
  ],
  "build-nix-multiarch": [
    BuildNixMultiArchBuildImageTemplate({}),
    BuildNixMultiArchCreateManifestTemplate({}),
  ],
};

await ExportCIComponentsGitLab(templates, fileHeader, {
  full: {
    devguard_artifact_name: Inputs.devguard_artifact_name,
    small_artifact_registry: Inputs.small_artifact_registry,
  },
  "container-lifecycle-with-base-image-inspection": {
    devguard_artifact_name: Inputs.devguard_artifact_name,
  },
});

// console.log("Finished");

/** GitHub */

const templatesGitHub: CIComponentGroupTemplateGitHub = {
  "secret-scanning": [SecretScanningTemplateGitHub({})],
  "build-image": [BuildOciImageTemplateGitHub({})],
  "container-scanning": [ContainerScanningTemplateGitHub({})],
  "software-composition-analysis": [SoftwareCompositionAnalysisTemplateGitHub({})],
  "static-application-security-testing": [StaticApplicationSecurityTestingTemplateGitHub({})],
  iac: [InfrastructureAsCodeScanningTemplateGitHub({})],
  deploy: [DeployTemplateGitHub({})],
  sign: [SignTemplateGitHub({})],
  attest: [AttestTemplateGitHub({})],
  "generate-tag": [GenerateTagTemplateGitHub({})],
  "push-oci-image": [PushOciImageTemplateGitHub({})],
  "sbom-upload": [SbomUploadTemplateGitHub({})],
  "vex-upload": [VexUploadTemplateGitHub({})],
  release: [ReleaseTemplateGitHub({})],
  "build-image-w-docker": [BuildOciImageWDockerTemplateGitHub({})],
  "create-manifest-multi-arch": [CreateManifestMultiArchTemplateGitHub({})],
  "discover-baseimage-attestations": [DiscoverBaseimageAttestationsTemplateGitHub({})],
  "sarif-upload": [SarifUploadTemplateGitHub({})],
  "zizmor-scanning": [ZizmorScanningTemplateGitHub({})],
  "build-nix": [BuildNixTemplateGitHub({})],
  "build-nix-multiarch-build": [BuildNixMultiArchBuildImageTemplateGitHub({})],
  "build-nix-multiarch-manifest": [BuildNixMultiArchCreateManifestTemplateGitHub({})],
};

await ExportCIComponentsGitHub(templatesGitHub, fileHeader);

/** GitHub Orchestrators */

const orchestratorsGitHub: Record<string, GitHubOrchestratorWorkflow> = {
  "code-scanning": {
    name: "Code Scanning",
    inputs: {
      "asset-name": {
        description: "Name of the asset to be scanned",
        type: "string",
        required: true,
      },
      "api-url": {
        type: "string",
        required: false,
        default: "https://api.devguard.org",
        description: "URL of the DevGuard API",
      },
      path: {
        description: "Path to the source code to be scanned",
        type: "string",
        required: false,
        default: "/github/workspace",
      },
      "web-ui": {
        type: "string",
        required: false,
        default: "https://app.devguard.org",
        description: "The URL of the DevGuard Web UI. This is used to link the results in the DevGuard Web UI.",
      },
      "fail-on-risk": {
        description: "Fail the job if a risk is higher than the configured threshold, e.g. critical, high, medium, low",
        type: "string",
        required: false,
        default: "",
      },
      "fail-on-cvss": {
        description: "Fail the job if a CVSS score is higher than the configured threshold, e.g. critical, high, medium, low",
        type: "string",
        required: false,
        default: "",
      },
      "continue-on-open-code-risk": {
        type: "boolean",
        required: false,
        default: true,
        description: "Whether to continue when open code risks are detected",
      },
    },
    secrets: {
      "devguard-token": {
        description: "DevGuard API token",
        required: true,
      },
    },
    jobs: {
      "call-secret-scanning": {
        uses: "./.github/workflows/secret-scanning.yml",
        permissions: {},
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          path: "${{ inputs.path }}",
          devguard_web_ui: "${{ inputs.web-ui }}",
          allow_failure: "${{ inputs.continue-on-open-code-risk }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
        },
      },
      "call-sast": {
        uses: "./.github/workflows/static-application-security-testing.yml",
        permissions: {},
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          path: "${{ inputs.path }}",
          devguard_web_ui: "${{ inputs.web-ui }}",
          allow_failure: "${{ inputs.continue-on-open-code-risk }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
        },
      },
      "call-iac": {
        uses: "./.github/workflows/iac.yml",
        permissions: {},
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          path: "${{ inputs.path }}",
          devguard_web_ui: "${{ inputs.web-ui }}",
          allow_failure: "${{ inputs.continue-on-open-code-risk }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
        },
      },
      "call-software-composition-analysis": {
        uses: "./.github/workflows/software-composition-analysis.yml",
        permissions: {},
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          path: "${{ inputs.path }}",
          fail_on_risk: "${{ inputs.fail-on-risk }}",
          fail_on_cvss: "${{ inputs.fail-on-cvss }}",
          devguard_web_ui: "${{ inputs.web-ui }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
        },
      },
    },
  },
  full: {
    name: "Full DevGuard Scan",
    inputs: {
      "asset-name": {
        description: "Name of the asset to be scanned",
        type: "string",
        required: true,
      },
      "api-url": {
        type: "string",
        required: false,
        default: "https://api.devguard.org",
        description: "URL of the DevGuard API",
      },
      path: {
        description: "Path to the source code to be scanned",
        type: "string",
        required: false,
        default: "/github/workspace",
      },
      "web-ui": {
        type: "string",
        required: false,
        default: "https://app.devguard.org",
        description: "The URL of the DevGuard Web UI. This is used to link the results in the DevGuard Web UI.",
      },
      "disable-artifact-registry-as-image-store": {
        required: false,
        default: false,
        type: "boolean",
        description:
          "If the artifact size is too big for your github usage quota, set this to true. This will push the image directly to the registry instead of uploading it as artifact.",
      },
      "image-destination-path": {
        description:
          "Path to the oci image to be scanned. Only necessary if deploy reusable workflow is not used and you would like to do further processing of the builded image.tar",
        type: "string",
        required: false,
        default: "image.tar",
      },
      image: {
        description: "oci image tag",
        type: "string",
        required: false,
        default: "",
      },
      "should-deploy": {
        description: "Should the deploy job run - publishing the image to the desired Container Registry",
        type: "boolean",
        required: false,
        default: true,
      },
      "image-suffix": {
        description:
          "Suffix for the image name. You probably need this if you are building multiple images. For example building a <abc>/scanner image and a <abc>/web image.",
        type: "string",
        required: false,
        default: "",
      },
      "fail-on-risk": {
        description: "Fail the job if a risk is higher than the configured threshold, e.g. critical, high, medium, low",
        type: "string",
        required: false,
        default: "",
      },
      "fail-on-cvss": {
        description: "Fail the job if a CVSS score is higher than the configured threshold, e.g. critical, high, medium, low",
        type: "string",
        required: false,
        default: "",
      },
      "continue-on-open-code-risk": {
        type: "boolean",
        required: false,
        default: true,
        description: "Whether to continue when open code risks are detected",
      },
      "artifact-name": {
        type: "string",
        required: false,
        default: "",
        description:
          "The name of the artifact you are building. This is useful when a single pipeline builds more than a single artifact like a container with a shell inside and one without. If you build a single artifact - leave it empty.",
      },
      "fetch-depth": {
        type: "number",
        required: false,
        default: 1,
        description: "Number of commits to fetch. 0 indicates all history for all branches and tags.",
      },
    },
    secrets: {
      "devguard-token": {
        description: "DevGuard API token",
        required: true,
      },
      "build-args": {
        description: "Build arguments. Useful to overwrite context and dockerfile. Maybe even add additional build args.",
        required: false,
      },
    },
    permissions: {
      contents: "read",
      packages: "write",
    },
    jobs: {
      "call-code-scanning": {
        uses: "./.github/workflows/code-scanning.yml",
        with: {
          "asset-name": "${{ inputs.asset-name }}",
          "api-url": "${{ inputs.api-url }}",
          path: "${{ inputs.path }}",
          "web-ui": "${{ inputs.web-ui }}",
          "fail-on-risk": "${{ inputs.fail-on-risk }}",
          "fail-on-cvss": "${{ inputs.fail-on-cvss }}",
          "continue-on-open-code-risk": "${{ inputs.continue-on-open-code-risk }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
        },
      },
      "call-build-image": {
        uses: "./.github/workflows/build-image.yml",
        with: {
          image_destination_path: "${{ inputs.image-destination-path }}",
          image: "${{ inputs.image }}",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          disable_artifact_registry_as_image_store: "${{ inputs.disable-artifact-registry-as-image-store }}",
          devguard_artifact_name: "${{ inputs.artifact-name }}",
          image_suffix: "${{ inputs.image-suffix }}",
          fetch_depth: "${{ inputs.fetch-depth }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
          "build-args": "${{ secrets.build-args }}",
        },
      },
      "call-container-scanning": {
        needs: ["call-build-image"],
        uses: "./.github/workflows/container-scanning.yml",
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_tar_path: "${{ inputs.image-destination-path }}",
          fetch_image_from_registry: "${{ inputs.disable-artifact-registry-as-image-store }}",
          fail_on_risk: "${{ inputs.fail-on-risk }}",
          fail_on_cvss: "${{ inputs.fail-on-cvss }}",
          devguard_web_ui: "${{ inputs.web-ui }}",
          devguard_artifact_name: "${{ inputs.artifact-name }}",
          image_suffix: "${{ inputs.image-suffix }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
        },
      },
      "call-deploy": {
        needs: ["call-build-image", "call-container-scanning", "call-code-scanning"],
        uses: "./.github/workflows/deploy.yml",
        with: {
          should_deploy: "${{ inputs.should-deploy }}",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_already_in_registry: "${{ inputs.disable-artifact-registry-as-image-store }}",
          image_suffix: "${{ inputs.image-suffix }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
        },
      },
      "call-sign": {
        needs: ["call-build-image", "call-container-scanning", "call-code-scanning", "call-deploy"],
        uses: "./.github/workflows/sign.yml",
        with: {
          should_deploy: "${{ inputs.should-deploy }}",
          devguard_api_url: "${{ inputs.api-url }}",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_artifact_name: "${{ inputs.artifact-name }}",
          image_suffix: "${{ inputs.image-suffix }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
        },
      },
      "call-attest": {
        needs: ["call-build-image", "call-container-scanning", "call-code-scanning", "call-deploy"],
        uses: "./.github/workflows/attest.yml",
        with: {
          should_deploy: "${{ inputs.should-deploy }}",
          devguard_api_url: "${{ inputs.api-url }}",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_artifact_name: "${{ inputs.artifact-name }}",
          image_suffix: "${{ inputs.image-suffix }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
        },
      },
    },
  },
  "container-lifecycle": {
    name: "Container Lifecycle",
    inputs: {
      "asset-name": { description: "Name of the asset", type: "string", required: true },
      "api-url": { type: "string", required: false, default: "https://api.devguard.org", description: "URL of the DevGuard API" },
      "web-ui": { type: "string", required: false, default: "https://app.devguard.org", description: "URL of the DevGuard Web UI" },
      "image-destination-path": { description: "Path to the OCI image tar file", type: "string", required: false, default: "image.tar" },
      image: { description: "OCI image tag", type: "string", required: false, default: "" },
      "disable-artifact-registry-as-image-store": { required: false, default: false, type: "boolean", description: "Push image directly to registry instead of uploading as artifact" },
      "image-suffix": { description: "Suffix for the image name when building multiple images", type: "string", required: false, default: "" },
      "artifact-name": { type: "string", required: false, default: "", description: "The name of the artifact you are building" },
      "should-deploy": { description: "Should the deploy job run", type: "boolean", required: false, default: true },
      "fail-on-risk": { description: "Fail if risk level reaches this threshold", type: "string", required: false, default: "" },
      "fail-on-cvss": { description: "Fail if CVSS score reaches this threshold", type: "string", required: false, default: "" },
      "fetch-depth": { type: "number", required: false, default: 1, description: "Number of commits to fetch" },
    },
    secrets: {
      "devguard-token": { description: "DevGuard API token", required: true },
      "build-args": { description: "Build arguments for Docker", required: false },
    },
    permissions: { contents: "read", packages: "write" },
    jobs: {
      "call-build-image": {
        uses: "./.github/workflows/build-image.yml",
        with: {
          image_destination_path: "${{ inputs.image-destination-path }}",
          image: "${{ inputs.image }}",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          disable_artifact_registry_as_image_store: "${{ inputs.disable-artifact-registry-as-image-store }}",
          devguard_artifact_name: "${{ inputs.artifact-name }}",
          image_suffix: "${{ inputs.image-suffix }}",
          fetch_depth: "${{ inputs.fetch-depth }}",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}", "build-args": "${{ secrets.build-args }}" },
      },
      "call-container-scanning": {
        needs: ["call-build-image"],
        uses: "./.github/workflows/container-scanning.yml",
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_tar_path: "${{ inputs.image-destination-path }}",
          fetch_image_from_registry: "${{ inputs.disable-artifact-registry-as-image-store }}",
          fail_on_risk: "${{ inputs.fail-on-risk }}",
          fail_on_cvss: "${{ inputs.fail-on-cvss }}",
          devguard_web_ui: "${{ inputs.web-ui }}",
          devguard_artifact_name: "${{ inputs.artifact-name }}",
          image_suffix: "${{ inputs.image-suffix }}",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "call-deploy": {
        needs: ["call-build-image", "call-container-scanning"],
        uses: "./.github/workflows/deploy.yml",
        with: {
          should_deploy: "${{ inputs.should-deploy }}",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_already_in_registry: "${{ inputs.disable-artifact-registry-as-image-store }}",
          image_suffix: "${{ inputs.image-suffix }}",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "call-sign": {
        needs: ["call-build-image", "call-container-scanning", "call-deploy"],
        uses: "./.github/workflows/sign.yml",
        with: {
          should_deploy: "${{ inputs.should-deploy }}",
          devguard_api_url: "${{ inputs.api-url }}",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_artifact_name: "${{ inputs.artifact-name }}",
          image_suffix: "${{ inputs.image-suffix }}",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "call-attest": {
        needs: ["call-build-image", "call-container-scanning", "call-deploy"],
        uses: "./.github/workflows/attest.yml",
        with: {
          should_deploy: "${{ inputs.should-deploy }}",
          devguard_api_url: "${{ inputs.api-url }}",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_artifact_name: "${{ inputs.artifact-name }}",
          image_suffix: "${{ inputs.image-suffix }}",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
    },
  },
  "container-lifecycle-nix": {
    name: "Container Lifecycle (Nix)",
    inputs: {
      "nix-target": { description: "Nix flake build target (e.g. devguardOCI)", type: "string", required: true },
      "image-name": { description: "Full OCI image name without tag", type: "string", required: true },
      "asset-name": { description: "DevGuard asset name for supply chain tracking", type: "string", required: true },
      "api-url": { type: "string", required: false, default: "https://api.devguard.org", description: "URL of the DevGuard API" },
      "web-ui": { type: "string", required: false, default: "https://app.devguard.org", description: "URL of the DevGuard Web UI" },
      "artifact-name-suffix": { description: "Suffix appended to artifact names", type: "string", required: false, default: "" },
      "should-deploy": { description: "Whether to push the image to the container registry", type: "boolean", required: false, default: true },
      "fail-on-risk": { description: "Fail if risk level reaches this threshold", type: "string", required: false, default: "" },
      "fail-on-cvss": { description: "Fail if CVSS score reaches this threshold", type: "string", required: false, default: "" },
      "nix-cache-substituter": { description: "Nix binary cache substituter URL", type: "string", required: false, default: "" },
      "nix-cache-public-key": { description: "Trusted public key for the Nix binary cache", type: "string", required: false, default: "" },
      "nix-cache-s3-endpoint": { description: "S3 API endpoint for pushing to the Nix cache", type: "string", required: false, default: "" },
      "nix-cache-s3-bucket": { description: "S3 bucket name for the Nix cache", type: "string", required: false, default: "nix" },
      "nix-cache-region": { description: "S3 region for the Nix cache bucket", type: "string", required: false, default: "garage" },
      "nix-version": { description: "Pinned Nix version", type: "string", required: false, default: "2.34.4" },
    },
    secrets: {
      "devguard-token": { description: "DevGuard API token", required: true },
      "nix-cache-secret-key": { description: "Nix binary cache signing secret key", required: false },
      "nix-cache-aws-access-key-id": { description: "AWS access key ID for the Nix S3 cache", required: false },
      "nix-cache-aws-secret-access-key": { description: "AWS secret access key for the Nix S3 cache", required: false },
    },
    permissions: { contents: "read", packages: "write" },
    jobs: {
      "build-image": {
        uses: "./.github/workflows/build-nix.yml",
        permissions: { contents: "read" },
        with: {
          nix_target: "${{ inputs.nix-target }}",
          image_name: "${{ inputs.image-name }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          nix_cache_substituter: "${{ inputs.nix-cache-substituter }}",
          nix_cache_public_key: "${{ inputs.nix-cache-public-key }}",
          nix_cache_s3_endpoint: "${{ inputs.nix-cache-s3-endpoint }}",
          nix_cache_s3_bucket: "${{ inputs.nix-cache-s3-bucket }}",
          nix_cache_region: "${{ inputs.nix-cache-region }}",
          nix_version: "${{ inputs.nix-version }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
          "nix-cache-secret-key": "${{ secrets.nix-cache-secret-key }}",
          "nix-cache-aws-access-key-id": "${{ secrets.nix-cache-aws-access-key-id }}",
          "nix-cache-aws-secret-access-key": "${{ secrets.nix-cache-aws-secret-access-key }}",
        },
      },
      "container-scanning": {
        needs: ["build-image"],
        uses: "./.github/workflows/container-scanning.yml",
        permissions: { contents: "read", "security-events": "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          devguard_web_ui: "${{ inputs.web-ui }}",
          fail_on_cvss: "${{ inputs.fail-on-cvss }}",
          fail_on_risk: "${{ inputs.fail-on-risk }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "deploy": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-image", "container-scanning"],
        uses: "./.github/workflows/deploy.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "sign": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-image", "container-scanning", "deploy"],
        uses: "./.github/workflows/sign.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "attest": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-image", "container-scanning", "deploy"],
        uses: "./.github/workflows/attest.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
    },
  },
  "full-nix": {
    name: "Full Nix Multi-Arch Pipeline",
    inputs: {
      "nix-target-amd64": {
        description: "Nix flake build target for amd64 (e.g. devguard-0-amd64)",
        type: "string",
        required: true,
      },
      "nix-target-arm64": {
        description: "Nix flake build target for arm64 (e.g. devguard-0-arm64)",
        type: "string",
        required: true,
      },
      "image-name": {
        description: "Full OCI image name without tag (e.g. ghcr.io/org/repo/image)",
        type: "string",
        required: true,
      },
      "artifact-name-suffix": {
        description: "Suffix appended to artifact names to avoid conflicts when building multiple images",
        type: "string",
        required: false,
        default: "",
      },
      "asset-name": {
        description: "DevGuard asset name for supply chain tracking",
        type: "string",
        required: true,
      },
      "api-url": {
        type: "string",
        required: false,
        default: "https://api.devguard.org",
        description: "URL of the DevGuard API",
      },
      "web-ui": {
        type: "string",
        required: false,
        default: "https://app.devguard.org",
        description: "URL of the DevGuard Web UI",
      },
      "fail-on-risk": {
        description: "Fail if risk level reaches this threshold (none|low|medium|high|critical)",
        type: "string",
        required: false,
        default: "critical",
      },
      "fail-on-cvss": {
        description: "Fail if CVSS score reaches this threshold (none|low|medium|high|critical)",
        type: "string",
        required: false,
        default: "critical",
      },
      "should-deploy": {
        description: "Whether to push the images and manifest to the container registry",
        type: "boolean",
        required: false,
        default: true,
      },
      "runner-amd64": {
        description: "GitHub Actions runner label for the amd64 build",
        type: "string",
        required: false,
        default: "ubuntu-latest",
      },
      "runner-arm64": {
        description: "GitHub Actions runner label for the arm64 build",
        type: "string",
        required: false,
        default: "ubuntu-24.04-arm",
      },
      "nix-cache-substituter": {
        description: "Nix binary cache substituter URL",
        type: "string",
        required: false,
        default: "",
      },
      "nix-cache-public-key": {
        description: "Trusted public key for the Nix binary cache",
        type: "string",
        required: false,
        default: "",
      },
      "nix-cache-s3-endpoint": {
        description: "S3 API endpoint for pushing to the Nix cache",
        type: "string",
        required: false,
        default: "",
      },
      "nix-cache-s3-bucket": {
        description: "S3 bucket name for the Nix cache",
        type: "string",
        required: false,
        default: "nix",
      },
      "nix-cache-region": {
        description: "S3 region for the Nix cache bucket",
        type: "string",
        required: false,
        default: "garage",
      },
      "nix-version": {
        description: "Pinned Nix version used by reusable build jobs",
        type: "string",
        required: false,
        default: "2.34.4",
      },
    },
    secrets: {
      "devguard-token": { description: "DevGuard API token", required: true },
      "nix-cache-secret-key": { description: "Nix binary cache signing secret key", required: false },
      "nix-cache-aws-access-key-id": { description: "AWS access key ID for the Nix S3 cache", required: false },
      "nix-cache-aws-secret-access-key": { description: "AWS secret access key for the Nix S3 cache", required: false },
    },
    permissions: {
      contents: "read",
      packages: "write",
    },
    jobs: {
      "build-amd64": {
        uses: "./.github/workflows/build-nix.yml",
        permissions: { contents: "read" },
        with: {
          nix_target: "${{ inputs.nix-target-amd64 }}",
          image_name: "${{ inputs.image-name }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-amd64",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          architecture: "amd64",
          runner: "${{ inputs.runner-amd64 }}",
          nix_cache_substituter: "${{ inputs.nix-cache-substituter }}",
          nix_cache_public_key: "${{ inputs.nix-cache-public-key }}",
          nix_cache_s3_endpoint: "${{ inputs.nix-cache-s3-endpoint }}",
          nix_cache_s3_bucket: "${{ inputs.nix-cache-s3-bucket }}",
          nix_cache_region: "${{ inputs.nix-cache-region }}",
          nix_version: "${{ inputs.nix-version }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
          "nix-cache-secret-key": "${{ secrets.nix-cache-secret-key }}",
          "nix-cache-aws-access-key-id": "${{ secrets.nix-cache-aws-access-key-id }}",
          "nix-cache-aws-secret-access-key": "${{ secrets.nix-cache-aws-secret-access-key }}",
        },
      },
      "build-arm64": {
        uses: "./.github/workflows/build-nix.yml",
        permissions: { contents: "read" },
        with: {
          nix_target: "${{ inputs.nix-target-arm64 }}",
          image_name: "${{ inputs.image-name }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-arm64",
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          architecture: "arm64",
          runner: "${{ inputs.runner-arm64 }}",
          nix_cache_substituter: "${{ inputs.nix-cache-substituter }}",
          nix_cache_public_key: "${{ inputs.nix-cache-public-key }}",
          nix_cache_s3_endpoint: "${{ inputs.nix-cache-s3-endpoint }}",
          nix_cache_s3_bucket: "${{ inputs.nix-cache-s3-bucket }}",
          nix_cache_region: "${{ inputs.nix-cache-region }}",
          nix_version: "${{ inputs.nix-version }}",
        },
        secrets: {
          "devguard-token": "${{ secrets.devguard-token }}",
          "nix-cache-secret-key": "${{ secrets.nix-cache-secret-key }}",
          "nix-cache-aws-access-key-id": "${{ secrets.nix-cache-aws-access-key-id }}",
          "nix-cache-aws-secret-access-key": "${{ secrets.nix-cache-aws-secret-access-key }}",
        },
      },
      "container-scanning-amd64": {
        needs: ["build-amd64"],
        uses: "./.github/workflows/container-scanning.yml",
        permissions: { contents: "read", "security-events": "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          devguard_web_ui: "${{ inputs.web-ui }}",
          fail_on_cvss: "${{ inputs.fail-on-cvss }}",
          fail_on_risk: "${{ inputs.fail-on-risk }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-amd64",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "container-scanning-arm64": {
        needs: ["build-arm64"],
        uses: "./.github/workflows/container-scanning.yml",
        permissions: { contents: "read", "security-events": "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          devguard_web_ui: "${{ inputs.web-ui }}",
          fail_on_cvss: "${{ inputs.fail-on-cvss }}",
          fail_on_risk: "${{ inputs.fail-on-risk }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-arm64",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "deploy-amd64": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-amd64", "container-scanning-amd64"],
        uses: "./.github/workflows/deploy.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-amd64",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "deploy-arm64": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-arm64", "container-scanning-arm64"],
        uses: "./.github/workflows/deploy.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-arm64",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "create-manifest": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-amd64", "build-arm64", "deploy-amd64", "deploy-arm64"],
        uses: "./.github/workflows/create-manifest-multi-arch.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          image_suffix: "${{ inputs.artifact-name-suffix }}",
        },
      },
      "sign-amd64": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-amd64", "create-manifest"],
        uses: "./.github/workflows/sign.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-amd64",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "sign-arm64": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-arm64", "create-manifest"],
        uses: "./.github/workflows/sign.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-arm64",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "attest-amd64": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-amd64", "create-manifest"],
        uses: "./.github/workflows/attest.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-amd64",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
      "attest-arm64": {
        if: "${{ inputs.should-deploy }}",
        needs: ["build-arm64", "create-manifest"],
        uses: "./.github/workflows/attest.yml",
        permissions: { contents: "read", packages: "write" },
        with: {
          devguard_asset_name: "${{ inputs.asset-name }}",
          devguard_api_url: "${{ inputs.api-url }}",
          image_suffix: "${{ inputs.artifact-name-suffix }}-arm64",
        },
        secrets: { "devguard-token": "${{ secrets.devguard-token }}" },
      },
    },
  },
};

await ExportGitHubOrchestratorWorkflows(orchestratorsGitHub, fileHeader);

// console.log("Finished");
