import { AttestJobInputs, AttestTemplate } from "./templates/attest";
import { BuildNixExtractScannerTemplate, BuildNixGenerateTagTemplate, BuildNixTemplate } from "./templates/build-nix";
import { BuildOciImageJobInputs, BuildOciImageTemplate } from "./templates/build-oci-image";
import { ContainerScanningJobInputs, ContainerScanningTemplate } from "./templates/container-scanning";
import { GenerateTagJobInputs, GenerateTagTemplate } from "./templates/generate-tag";
import { IaCJobInputs, InfrastructureAsCodeScanningTemplate } from "./templates/infrastructure-as-code-scanning";
import { PushOciImageJobInputs, PushOciImageTemplate } from "./templates/push-oci-image";
import { SignOciImageJobInputs, SignOciImageTemplate } from "./templates/sign-oci-image";
import { SCAJobInputs, SoftwareCompositionAnalysisTemplate } from "./templates/software-composition-analysis";
import {
  SASTJobInputs,
  StaticApplicationSecurityTestingTemplate,
} from "./templates/static-application-security-testing";
import { CIComponentGroupTemplateGitHub, CIComponentGroupTemplateGitLab } from "./lib/types";
import { ExportCIComponentsGitHub, ExportCIComponentsGitLab } from "./lib/utils";
import { BuildOciImageWDockerTemplate } from "./templates/build-oci-image-w-docker";
import { CreateManifestMultiArchTemplate } from "./templates/create-manifest-multi-arch";
import { DiscoverBaseimageAttestationsTemplate } from "./templates/discover-baseimage-attestations";
import { Inputs } from "./templates/inputs";
import { ReleaseTemplate } from "./templates/release";
import { SarifUploadTemplate } from "./templates/sarif-upload";
import { SbomUploadTemplate } from "./templates/sbom-upload";
import { SourceProvenanceTemplate } from "./templates/source-provenance-attestation";
import { VexUploadTemplate } from "./templates/vex-upload";
import {
  SecretScanningTemplateGitHub,
  SecretScanningTemplateGitLab,
  SecretScanningJobInputsGitLab,
} from "./templates/secret-scanning";
import { BuildOciImageTemplateGitHub } from "./templates/build-oci-image";
import { ContainerScanningTemplateGitHub } from "./templates/container-scanning";
import { SoftwareCompositionAnalysisTemplateGitHub } from "./templates/software-composition-analysis";
import { StaticApplicationSecurityTestingTemplateGitHub } from "./templates/static-application-security-testing";
import { InfrastructureAsCodeScanningTemplateGitHub } from "./templates/infrastructure-as-code-scanning";
import { DeployTemplateGitHub, DeployTemplateGitLab } from "./templates/deploy";
import { SignTemplateGitHub } from "./templates/sign-oci-image";
import { AttestTemplateGitHub } from "./templates/attest";
import { GenerateTagTemplateGitHub } from "./templates/generate-tag";
import { PushOciImageTemplateGitHub } from "./templates/push-oci-image";
import { SbomUploadTemplateGitHub } from "./templates/sbom-upload";
import { VexUploadTemplateGitHub } from "./templates/vex-upload";
import { ReleaseTemplateGitHub } from "./templates/release";
import { BuildOciImageWDockerTemplateGitHub } from "./templates/build-oci-image-w-docker";
import { CreateManifestMultiArchTemplateGitHub } from "./templates/create-manifest-multi-arch";
import { DiscoverBaseimageAttestationsTemplateGitHub } from "./templates/discover-baseimage-attestations";
import { SarifUploadTemplateGitHub } from "./templates/sarif-upload";
import {
  BuildNixMultiArchBuildImageTemplateGitHub,
  BuildNixMultiArchCreateManifestTemplateGitHub,
} from "./templates/build-nix-multiarch";
import { BuildNixTemplateGitHub } from "./templates/build-nix";

// const fileHeader = `# Copyright 2025-${new Date().getFullYear()} l3montree GmbH.
const fileHeader = `# Copyright 2025 l3montree GmbH.
# SPDX-License-Identifier: AGPL-3.0

# This file is automatically generated. Do not edit directly.
`;

// ── full ──────────────────────────────────────────────────────────────────────
const fullGenerateTag = GenerateTagTemplate({
  stage: "oci-image",
  git_strategy: GenerateTagJobInputs.git_strategy.default,
});
const fullBuildOciImage = BuildOciImageTemplate({
  stage: "oci-image",
  git_strategy: BuildOciImageJobInputs.git_strategy.default,
  image: BuildOciImageJobInputs.image.default,
  image_tag: "$IMAGE_TAG",
  needs: [fullGenerateTag.name],
  dependencies: [fullGenerateTag.name],
  push_image: "$[[ inputs.small_artifact_registry ]]",
});
const fullContrainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: ContainerScanningJobInputs.git_strategy.default,
  image_tag: "",
  devguard_artifact_name: "$ARTIFACT_NAME",
  needs: [fullGenerateTag.name, fullBuildOciImage.name],
  dependencies: [fullGenerateTag.name, fullBuildOciImage.name],
});
const fullPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  image: PushOciImageJobInputs.image.default,
  image_tag: "$IMAGE_TAG",
  needs: [fullGenerateTag.name, fullBuildOciImage.name, fullContrainerScanning.name],
  dependencies: [fullGenerateTag.name, fullBuildOciImage.name, fullContrainerScanning.name],
  disable_job: "$[[ inputs.small_artifact_registry ]]",
});
const fullSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: SignOciImageJobInputs.git_strategy.default,
  image: "$IMAGE_TAG",
  needs: [fullGenerateTag.name, fullBuildOciImage.name, { job: fullPushOciImage.name, optional: true }],
  dependencies: [fullGenerateTag.name, fullBuildOciImage.name, fullPushOciImage.name],
});
const fullSourceProvenanceAttestation = SourceProvenanceTemplate({
  stage: AttestJobInputs.stage.default,
});
const fullAttest = AttestTemplate({
  stage: AttestJobInputs.stage.default,
  devguard_artifact_name: "$ARTIFACT_NAME",
  image: "$IMAGE_TAG",
  needs: [
    fullGenerateTag.name,
    fullSignOciImage.name,
    fullBuildOciImage.name,
    { job: "source-provenance-artifacts", optional: true },
  ],
  attestations: [
    {
      source:
        "$[[ inputs.devguard_api_url ]]/api/v1/organizations/$[[ inputs.devguard_asset_name ]]/refs/COMMIT_REF/artifacts/ARTIFACT_NAME/sbom.json/",
      predicate_type: "https://cyclonedx.org/bom",
    },
    {
      source:
        "$[[ inputs.devguard_api_url ]]/api/v1/organizations/$[[ inputs.devguard_asset_name ]]/refs/COMMIT_REF/artifacts/ARTIFACT_NAME/vex.json/",
      predicate_type: "https://cyclonedx.org/vex",
    },
    {
      source:
        "$[[ inputs.devguard_api_url ]]/api/v1/organizations/$[[ inputs.devguard_asset_name ]]/refs/COMMIT_REF/sarif.json/",
      predicate_type: "https://www.schemastore.org/schemas/json/sarif-2.1.0.json",
    },
    {
      source: "build.provenance.json",
      predicate_type: "https://slsa.dev/provenance/v1",
    },
    {
      source: "artifacts/attestation-report.json",
      predicate_type:
        "https://gitlab.opencode.de/open-code/badgebackend/source-provenance-attestation-service/-/raw/main/schema/source-provenance-schema-1.0.1.json",
    },
  ],
});

// ── container-lifecycle ───────────────────────────────────────────────────────
const clGenerateTag = GenerateTagTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
});
const clBuildOciImage = BuildOciImageTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clGenerateTag.name],
  dependencies: [clGenerateTag.name],
});
const clContainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image_tar_path: "image.tar",
  needs: [clBuildOciImage.name],
  dependencies: [clBuildOciImage.name],
});
const clPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clGenerateTag.name, clBuildOciImage.name, clContainerScanning.name],
  dependencies: [clGenerateTag.name, clBuildOciImage.name, clContainerScanning.name],
});
const clSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [clGenerateTag.name, clPushOciImage.name],
  dependencies: [clGenerateTag.name, clPushOciImage.name],
});
const clAttest = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  needs: [clGenerateTag.name, clPushOciImage.name, clBuildOciImage.name, clContainerScanning.name],
});

// ── container-lifecycle-nix ───────────────────────────────────────────────────
const clnExtractScanner = BuildNixExtractScannerTemplate({});
const clnGenerateTag = BuildNixGenerateTagTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
});
const clnBuildOciImage = BuildNixTemplate({
  stage: "oci-image",
  image: "image.tar",
  needs: [clnGenerateTag.name],
  dependencies: [clnGenerateTag.name],
});
const clnContainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image_tar_path: "image.tar",
  needs: [clnGenerateTag.name, clnBuildOciImage.name],
  dependencies: [clnGenerateTag.name, clnBuildOciImage.name],
});
const clnPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clnGenerateTag.name, clnBuildOciImage.name, clnContainerScanning.name],
  dependencies: [clnGenerateTag.name, clnBuildOciImage.name, clnContainerScanning.name],
});
const clnSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [clnGenerateTag.name, clnPushOciImage.name],
  dependencies: [clnGenerateTag.name, clnPushOciImage.name],
});
const clnAttest = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  needs: [clnGenerateTag.name, clnPushOciImage.name, clnBuildOciImage.name, clnContainerScanning.name],
});

// ── push-and-attest ───────────────────────────────────────────────────────────
const paGenerateTag = GenerateTagTemplate({
  stage: "$[[ inputs.build_stage ]]",
  git_strategy: "fetch",
});
const paPushOciImage = PushOciImageTemplate({
  stage: "$[[ inputs.build_stage ]]",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [paGenerateTag.name, "$[[ inputs.build_job_name ]]"],
  dependencies: [paGenerateTag.name, "$[[ inputs.build_job_name ]]"],
});
const paSignOciImage = SignOciImageTemplate({
  stage: "$[[ inputs.attest_stage ]]",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [paGenerateTag.name, paPushOciImage.name],
  dependencies: [paGenerateTag.name, paPushOciImage.name],
});
const paAttest = AttestTemplate({
  stage: "$[[ inputs.attest_stage ]]",
  git_strategy: "none",
  needs: [paGenerateTag.name, "$[[ inputs.build_job_name ]]", paPushOciImage.name],
});

// ── container-scanning-and-attest ─────────────────────────────────────────────
const csaGenerateTag = GenerateTagTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
});
const csaContainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  needs: [csaGenerateTag.name, "$[[ inputs.build_job_name ]]"],
  dependencies: [csaGenerateTag.name, "$[[ inputs.build_job_name ]]"],
});
const csaPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [csaGenerateTag.name, csaContainerScanning.name, "$[[ inputs.build_job_name ]]"],
  dependencies: [csaGenerateTag.name, csaContainerScanning.name, "$[[ inputs.build_job_name ]]"],
});
const csaSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [csaGenerateTag.name, csaPushOciImage.name],
  dependencies: [csaGenerateTag.name, csaPushOciImage.name],
});
const csaAttest = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  needs: [csaGenerateTag.name, "$[[ inputs.build_job_name ]]", csaContainerScanning.name, csaPushOciImage.name],
});

// ── build-nix-multiarch ───────────────────────────────────────────────────────
const bnmaExtractScannerAmd64 = BuildNixExtractScannerTemplate({ job_suffix: "-amd64" });
const bnmaExtractScannerArm64 = BuildNixExtractScannerTemplate({ job_suffix: "-arm64" });

const bnmaGenerateTagAmd64 = BuildNixGenerateTagTemplate({
  stage: "build",
  git_strategy: "fetch",
  job_suffix: "-amd64",
  architecture: "amd64",
  runner_tags: ["$[[ inputs.amd64_runner_tag ]]"],
  needs: [bnmaExtractScannerAmd64.name],
  dependencies: [bnmaExtractScannerAmd64.name],
});
const bnmaBuildAmd64 = BuildNixTemplate({
  stage: "build",
  image: "image-amd64.tar",
  job_suffix: "-amd64",
  nix_target: "$[[ inputs.nix_target_amd64 ]]",
  runner_tags: ["$[[ inputs.amd64_runner_tag ]]"],
  needs: [bnmaGenerateTagAmd64.name],
  dependencies: [bnmaGenerateTagAmd64.name],
});
const bnmaContainerScanningAmd64 = ContainerScanningTemplate({
  stage: "test",
  git_strategy: "fetch",
  job_suffix: "-amd64",
  image_tar_path: "image-amd64.tar",
  runner_tags: ["$[[ inputs.amd64_runner_tag ]]"],
  needs: [bnmaGenerateTagAmd64.name, bnmaBuildAmd64.name],
  dependencies: [bnmaGenerateTagAmd64.name, bnmaBuildAmd64.name],
});
const bnmaPushAmd64 = PushOciImageTemplate({
  stage: "deploy",
  git_strategy: "none",
  image: "image-amd64.tar",
  job_suffix: "-amd64",
  runner_tags: ["$[[ inputs.amd64_runner_tag ]]"],
  needs: [bnmaGenerateTagAmd64.name, bnmaBuildAmd64.name, bnmaContainerScanningAmd64.name],
  dependencies: [bnmaGenerateTagAmd64.name, bnmaBuildAmd64.name, bnmaContainerScanningAmd64.name],
});
const bnmaSignAmd64 = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  job_suffix: "-amd64",
  runner_tags: ["$[[ inputs.amd64_runner_tag ]]"],
  needs: [bnmaGenerateTagAmd64.name, bnmaPushAmd64.name],
  dependencies: [bnmaGenerateTagAmd64.name, bnmaPushAmd64.name],
});
const bnmaAttestAmd64 = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  job_suffix: "-amd64",
  needs: [bnmaGenerateTagAmd64.name, bnmaBuildAmd64.name, bnmaPushAmd64.name],
});

const bnmaGenerateTagArm64 = BuildNixGenerateTagTemplate({
  stage: "build",
  git_strategy: "fetch",
  job_suffix: "-arm64",
  architecture: "arm64",
  runner_tags: ["$[[ inputs.arm64_runner_tag ]]"],
  needs: [bnmaExtractScannerArm64.name],
  dependencies: [bnmaExtractScannerArm64.name],
});
const bnmaBuildArm64 = BuildNixTemplate({
  stage: "build",
  image: "image-arm64.tar",
  job_suffix: "-arm64",
  nix_target: "$[[ inputs.nix_target_arm64 ]]",
  runner_tags: ["$[[ inputs.arm64_runner_tag ]]"],
  needs: [bnmaGenerateTagArm64.name],
  dependencies: [bnmaGenerateTagArm64.name],
});
const bnmaContainerScanningArm64 = ContainerScanningTemplate({
  stage: "test",
  git_strategy: "fetch",
  job_suffix: "-arm64",
  image_tar_path: "image-arm64.tar",
  runner_tags: ["$[[ inputs.arm64_runner_tag ]]"],
  needs: [bnmaGenerateTagArm64.name, bnmaBuildArm64.name],
  dependencies: [bnmaGenerateTagArm64.name, bnmaBuildArm64.name],
});
const bnmaPushArm64 = PushOciImageTemplate({
  stage: "deploy",
  git_strategy: "none",
  image: "image-arm64.tar",
  job_suffix: "-arm64",
  runner_tags: ["$[[ inputs.arm64_runner_tag ]]"],
  needs: [bnmaGenerateTagArm64.name, bnmaBuildArm64.name, bnmaContainerScanningArm64.name],
  dependencies: [bnmaGenerateTagArm64.name, bnmaBuildArm64.name, bnmaContainerScanningArm64.name],
});
const bnmaSignArm64 = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  job_suffix: "-arm64",
  runner_tags: ["$[[ inputs.arm64_runner_tag ]]"],
  needs: [bnmaGenerateTagArm64.name, bnmaPushArm64.name],
  dependencies: [bnmaGenerateTagArm64.name, bnmaPushArm64.name],
});
const bnmaAttestArm64 = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  job_suffix: "-arm64",
  needs: [bnmaGenerateTagArm64.name, bnmaBuildArm64.name, bnmaPushArm64.name],
});

const bnmaCreateManifest = CreateManifestMultiArchTemplate({
  stage: "attestation",
  artifacts_subdirectory: ".",
  needs: [bnmaPushAmd64.name, bnmaPushArm64.name],
  dependencies: [bnmaGenerateTagAmd64.name, bnmaGenerateTagArm64.name, bnmaPushAmd64.name, bnmaPushArm64.name],
});
const bnmaSignManifest = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$MANIFEST_IMAGE_TAG",
  job_suffix: "-manifest",
  needs: [bnmaCreateManifest.name],
  dependencies: [bnmaCreateManifest.name],
});

// ── container-lifecycle-with-base-image-inspection ────────────────────────────
const clbiDiscoverAttestations = DiscoverBaseimageAttestationsTemplate({
  stage: "oci-image",
  allow_failure: true,
});
const clbiGenerateTag = GenerateTagTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
});
const clbiBuildOciImage = BuildOciImageTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clbiGenerateTag.name],
  dependencies: [clbiGenerateTag.name],
});
const clbiContainerScanning = ContainerScanningTemplate({
  stage: "oci-image",
  git_strategy: "fetch",
  image_tar_path: "image.tar",
  needs: [clbiBuildOciImage.name],
  dependencies: [clbiBuildOciImage.name],
});
const clbiPushOciImage = PushOciImageTemplate({
  stage: "oci-image",
  git_strategy: "none",
  image: "image.tar",
  image_tag: "$IMAGE_TAG",
  needs: [clbiGenerateTag.name, clbiBuildOciImage.name, clbiContainerScanning.name],
  dependencies: [clbiGenerateTag.name, clbiBuildOciImage.name, clbiContainerScanning.name],
});
const clbiSignOciImage = SignOciImageTemplate({
  stage: "attestation",
  git_strategy: "none",
  image: "$IMAGE_TAG",
  needs: [clbiGenerateTag.name, clbiPushOciImage.name],
  dependencies: [clbiGenerateTag.name, clbiPushOciImage.name],
});
const clbiAttest = AttestTemplate({
  stage: "attestation",
  git_strategy: "none",
  needs: [clbiGenerateTag.name, clbiPushOciImage.name, clbiBuildOciImage.name, clbiContainerScanning.name],
});
// sbom/vex upload depend on discover_baseimage_attestations; file paths use $[[ inputs.output ]] (added via inputOverrides)
const clbiSbomUpload = SbomUploadTemplate({
  stage: "attestation",
  allow_failure: true,
  git_strategy: "none",
  sbom_file: "$[[ inputs.output ]]/attestation-bom.json",
  devguard_origin: "BASE_IMAGE_SBOM",
  needs: [clbiDiscoverAttestations.name],
  dependencies: [clbiDiscoverAttestations.name],
});
const clbiVexUpload = VexUploadTemplate({
  stage: "attestation",
  allow_failure: true,
  git_strategy: "none",
  vex_file: "$[[ inputs.output ]]/attestation-vex.json",
  devguard_origin: "BASE_IMAGE_VEX",
  needs: [clbiDiscoverAttestations.name, clbiSbomUpload.name],
  dependencies: [clbiDiscoverAttestations.name, clbiSbomUpload.name],
});

const templates: CIComponentGroupTemplateGitLab = {
  // ── Individual job templates ──────────────────────────────────────────────
  // "source-provenance-attestation": [
  //     SourceProvenanceTemplate({}),
  // ],

  attest: [AttestTemplate({})],
  "secret-scanning": [SecretScanningTemplateGitLab({})],
  "static-application-security-testing": [StaticApplicationSecurityTestingTemplate({})],
  "infrastructure-as-code-scanning": [InfrastructureAsCodeScanningTemplate({})],
  "software-composition-analysis": [SoftwareCompositionAnalysisTemplate({})],
  "generate-tag": [GenerateTagTemplate({})],
  "build-oci-image": [BuildOciImageTemplate({})],
  "build-oci-image-w-docker": [BuildOciImageWDockerTemplate({})],
  "container-scanning": [ContainerScanningTemplate({})],
  "push-oci-image": [PushOciImageTemplate({})],
  "sign-oci-image": [SignOciImageTemplate({})],
  "create-manifest-multi-arch": [CreateManifestMultiArchTemplate({})],
  "sarif-upload": [SarifUploadTemplate({})],
  "sbom-upload": [SbomUploadTemplate({})],
  "vex-upload": [VexUploadTemplate({})],
  "discover-baseimage-attestations": [DiscoverBaseimageAttestationsTemplate({})],
  release: [ReleaseTemplate({})],
  deploy: [DeployTemplateGitLab({})],

  // ── Orchestration templates ───────────────────────────────────────────────
  full: [
    fullSourceProvenanceAttestation,
    SecretScanningTemplateGitLab({
      git_strategy: SecretScanningJobInputsGitLab.git_strategy.default,
    }),
    StaticApplicationSecurityTestingTemplate({
      git_strategy: SASTJobInputs.git_strategy.default,
    }),
    InfrastructureAsCodeScanningTemplate({
      git_strategy: IaCJobInputs.git_strategy.default,
    }),
    SoftwareCompositionAnalysisTemplate({
      git_strategy: SCAJobInputs.git_strategy.default,
    }),
    fullGenerateTag,
    fullBuildOciImage,
    fullContrainerScanning,
    fullPushOciImage,
    fullSignOciImage,
    fullAttest,
  ],
  "container-lifecycle": [
    clGenerateTag,
    clBuildOciImage,
    clContainerScanning,
    clPushOciImage,
    clSignOciImage,
    clAttest,
  ],
  "container-lifecycle-nix": [
    clnExtractScanner,
    clnGenerateTag,
    clnBuildOciImage,
    clnContainerScanning,
    clnPushOciImage,
    clnSignOciImage,
    clnAttest,
  ],
  "push-and-attest": [paGenerateTag, paPushOciImage, paSignOciImage, paAttest],
  "container-scanning-and-attest": [csaGenerateTag, csaContainerScanning, csaPushOciImage, csaSignOciImage, csaAttest],
  "container-lifecycle-with-base-image-inspection": [
    clbiDiscoverAttestations,
    clbiGenerateTag,
    clbiBuildOciImage,
    clbiContainerScanning,
    clbiPushOciImage,
    clbiSignOciImage,
    clbiAttest,
    clbiSbomUpload,
    clbiVexUpload,
  ],
  "build-nix": [BuildNixExtractScannerTemplate({}), BuildNixGenerateTagTemplate({}), BuildNixTemplate({})],
  "build-nix-multiarch": [
    bnmaExtractScannerAmd64,
    bnmaExtractScannerArm64,
    bnmaGenerateTagAmd64,
    bnmaBuildAmd64,
    bnmaContainerScanningAmd64,
    bnmaPushAmd64,
    bnmaSignAmd64,
    bnmaAttestAmd64,
    bnmaGenerateTagArm64,
    bnmaBuildArm64,
    bnmaContainerScanningArm64,
    bnmaPushArm64,
    bnmaSignArm64,
    bnmaAttestArm64,
    bnmaCreateManifest,
    bnmaSignManifest,
  ],
};

await ExportCIComponentsGitLab(templates, fileHeader, {
  full: {
    devguard_artifact_name: Inputs.devguard_artifact_name,
    small_artifact_registry: Inputs.small_artifact_registry,
  },
  "container-lifecycle-with-base-image-inspection": {
    devguard_artifact_name: Inputs.devguard_artifact_name,
  },
  "push-and-attest": {
    build_job_name: {
      description: "Name of the build job to depend on" as const,
    },
    build_stage: {
      description: "Pipeline stage for the push jobs (e.g. build, oci-image)" as const,
      default: "oci-image" as const,
    },
    attest_stage: {
      description: "Pipeline stage for the sign/attest jobs (e.g. test, attestation)" as const,
      default: "attestation" as const,
    },
  },
  "build-nix-multiarch": {
    nix_target_amd64: {
      description: "Nix flake build target for amd64 (e.g. coreutils-amd64)" as const,
    },
    nix_target_arm64: {
      description: "Nix flake build target for arm64 (e.g. coreutils-arm64)" as const,
    },
    amd64_runner_tag: {
      description: "Runner tag for amd64 builds" as const,
      default: "" as const,
    },
    arm64_runner_tag: {
      description: "Runner tag for arm64 builds" as const,
      default: "" as const,
    },
    image_tag: {
      description: "OCI image tag (e.g. registry.example.com/org/image:tag)" as const,
      default: "" as const,
    },
  },
});

// console.log("Finished");

/** GitHub */

// ── code-scanning orchestrator ────────────────────────────────────────────────
const ghCsSecretScanning = SecretScanningTemplateGitHub({});
const ghCsSast = StaticApplicationSecurityTestingTemplateGitHub({});
const ghCsIac = InfrastructureAsCodeScanningTemplateGitHub({});
const ghCsSca = SoftwareCompositionAnalysisTemplateGitHub({});

// ── container-lifecycle orchestrator ──────────────────────────────────────────
const ghClBuild = BuildOciImageTemplateGitHub({});
const ghClScan = ContainerScanningTemplateGitHub({});
ghClScan.job.needs = ["devguard_build_oci_image"];
const ghClDeploy = DeployTemplateGitHub({});
ghClDeploy.job.needs = ["devguard_build_oci_image", "devguard_container_scanning"];
const ghClSign = SignTemplateGitHub({ image: "image.tar" });
ghClSign.job.needs = ["devguard_build_oci_image", "devguard_container_scanning", "devguard_deploy"];
const ghClAttest = AttestTemplateGitHub({});
ghClAttest.job.needs = ["devguard_build_oci_image", "devguard_container_scanning", "devguard_deploy"];

// ── full orchestrator ─────────────────────────────────────────────────────────
const ghFullSecretScanning = SecretScanningTemplateGitHub({});
const ghFullSast = StaticApplicationSecurityTestingTemplateGitHub({});
const ghFullIac = InfrastructureAsCodeScanningTemplateGitHub({});
const ghFullSca = SoftwareCompositionAnalysisTemplateGitHub({});
const ghFullBuild = BuildOciImageTemplateGitHub({});
const ghFullScan = ContainerScanningTemplateGitHub({});
ghFullScan.job.needs = ["devguard_build_oci_image"];
const ghFullDeploy = DeployTemplateGitHub({});
ghFullDeploy.job.needs = [
  "devguard_build_oci_image",
  "devguard_container_scanning",
  "devguard_secret_scanning",
  "devguard_static_application_security_testing",
  "devguard_infrastructure_as_code",
  "devguard_software_composition_analysis",
];
const ghFullSign = SignTemplateGitHub({ image: "image.tar" });
ghFullSign.job.needs = [
  "devguard_build_oci_image",
  "devguard_container_scanning",
  "devguard_secret_scanning",
  "devguard_static_application_security_testing",
  "devguard_infrastructure_as_code",
  "devguard_software_composition_analysis",
  "devguard_deploy",
];
const ghFullAttest = AttestTemplateGitHub({});
ghFullAttest.job.needs = [
  "devguard_build_oci_image",
  "devguard_container_scanning",
  "devguard_secret_scanning",
  "devguard_static_application_security_testing",
  "devguard_infrastructure_as_code",
  "devguard_software_composition_analysis",
  "devguard_deploy",
];

// ── container-lifecycle-nix orchestrator ──────────────────────────────────────
const ghClnBuild = BuildNixTemplateGitHub({});
const ghClnScan = ContainerScanningTemplateGitHub({});
ghClnScan.job.needs = ["devguard_build_nix"];
const ghClnDeploy = DeployTemplateGitHub({});
ghClnDeploy.job.needs = ["devguard_build_nix", "devguard_container_scanning"];
const ghClnSign = SignTemplateGitHub({ image: "image.tar" });
ghClnSign.job.needs = ["devguard_build_nix", "devguard_container_scanning", "devguard_deploy"];
const ghClnAttest = AttestTemplateGitHub({});
ghClnAttest.job.needs = ["devguard_build_nix", "devguard_container_scanning", "devguard_deploy"];

// ── full-nix orchestrator ─────────────────────────────────────────────────────
const ghFnBuildAmd64 = BuildNixTemplateGitHub({
  nix_target: "${{ inputs.nix_target_amd64 }}",
  image_suffix: "${{ inputs.artifact_name_suffix }}-amd64",
  architecture: "amd64",
  runner: "${{ inputs.runner_amd64 }}",
});
ghFnBuildAmd64.name = "devguard:build-nix-amd64";

const ghFnBuildArm64 = BuildNixTemplateGitHub({
  nix_target: "${{ inputs.nix_target_arm64 }}",
  image_suffix: "${{ inputs.artifact_name_suffix }}-arm64",
  architecture: "arm64",
  runner: "${{ inputs.runner_arm64 }}",
});
ghFnBuildArm64.name = "devguard:build-nix-arm64";

const ghFnScanAmd64 = ContainerScanningTemplateGitHub({
  image_suffix: "${{ inputs.artifact_name_suffix }}-amd64",
});
ghFnScanAmd64.name = "devguard:container-scanning-amd64";
ghFnScanAmd64.job.needs = ["devguard_build_nix_amd64"];

const ghFnScanArm64 = ContainerScanningTemplateGitHub({
  image_suffix: "${{ inputs.artifact_name_suffix }}-arm64",
});
ghFnScanArm64.name = "devguard:container-scanning-arm64";
ghFnScanArm64.job.needs = ["devguard_build_nix_arm64"];

const ghFnDeployAmd64 = DeployTemplateGitHub({
  image_suffix: "${{ inputs.artifact_name_suffix }}-amd64",
});
ghFnDeployAmd64.name = "devguard:deploy-amd64";
ghFnDeployAmd64.job.needs = ["devguard_build_nix_amd64", "devguard_container_scanning_amd64"];

const ghFnDeployArm64 = DeployTemplateGitHub({
  image_suffix: "${{ inputs.artifact_name_suffix }}-arm64",
});
ghFnDeployArm64.name = "devguard:deploy-arm64";
ghFnDeployArm64.job.needs = ["devguard_build_nix_arm64", "devguard_container_scanning_arm64"];

const ghFnManifest = CreateManifestMultiArchTemplateGitHub({
  image_suffix: "${{ inputs.artifact_name_suffix }}",
});
ghFnManifest.job.needs = ["devguard_deploy_amd64", "devguard_deploy_arm64"];

const ghFnSignAmd64 = SignTemplateGitHub({
  image: "image.tar",
  image_suffix: "${{ inputs.artifact_name_suffix }}-amd64",
});
ghFnSignAmd64.name = "devguard:sign-amd64";
ghFnSignAmd64.job.needs = ["devguard_build_nix_amd64", "devguard_create_manifest_multi_arch"];

const ghFnSignArm64 = SignTemplateGitHub({
  image: "image.tar",
  image_suffix: "${{ inputs.artifact_name_suffix }}-arm64",
});
ghFnSignArm64.name = "devguard:sign-arm64";
ghFnSignArm64.job.needs = ["devguard_build_nix_arm64", "devguard_create_manifest_multi_arch"];

const ghFnAttestAmd64 = AttestTemplateGitHub({
  image_suffix: "${{ inputs.artifact_name_suffix }}-amd64",
});
ghFnAttestAmd64.name = "devguard:attest-amd64";
ghFnAttestAmd64.job.needs = ["devguard_build_nix_amd64", "devguard_create_manifest_multi_arch"];

const ghFnAttestArm64 = AttestTemplateGitHub({
  image_suffix: "${{ inputs.artifact_name_suffix }}-arm64",
});
ghFnAttestArm64.name = "devguard:attest-arm64";
ghFnAttestArm64.job.needs = ["devguard_build_nix_arm64", "devguard_create_manifest_multi_arch"];

const templatesGitHub: CIComponentGroupTemplateGitHub = {
  // Individual reusable component workflows
  "secret-scanning": [SecretScanningTemplateGitHub({})],
  "build-image": [BuildOciImageTemplateGitHub({})],
  "container-scanning": [ContainerScanningTemplateGitHub({})],
  "software-composition-analysis": [SoftwareCompositionAnalysisTemplateGitHub({})],
  "static-application-security-testing": [StaticApplicationSecurityTestingTemplateGitHub({})],
  iac: [InfrastructureAsCodeScanningTemplateGitHub({})],
  deploy: [DeployTemplateGitHub({})],
  sign: [SignTemplateGitHub({})],
  attest: [AttestTemplateGitHub({})],
  "generate-tag": [GenerateTagTemplateGitHub({})],
  "push-oci-image": [PushOciImageTemplateGitHub({})],
  "sbom-upload": [SbomUploadTemplateGitHub({})],
  "vex-upload": [VexUploadTemplateGitHub({})],
  release: [ReleaseTemplateGitHub({})],
  "build-image-w-docker": [BuildOciImageWDockerTemplateGitHub({})],
  "create-manifest-multi-arch": [CreateManifestMultiArchTemplateGitHub({})],
  "discover-baseimage-attestations": [DiscoverBaseimageAttestationsTemplateGitHub({})],
  "sarif-upload": [SarifUploadTemplateGitHub({})],
  "build-nix": [BuildNixTemplateGitHub({})],
  "build-nix-multiarch-build": [BuildNixMultiArchBuildImageTemplateGitHub({})],
  "build-nix-multiarch-manifest": [BuildNixMultiArchCreateManifestTemplateGitHub({})],
  // Orchestrator workflows (inline, no uses:)
  "code-scanning": [ghCsSecretScanning, ghCsSast, ghCsIac, ghCsSca],
  "container-lifecycle": [ghClBuild, ghClScan, ghClDeploy, ghClSign, ghClAttest],
  full: [ghFullSecretScanning, ghFullSast, ghFullIac, ghFullSca, ghFullBuild, ghFullScan, ghFullDeploy, ghFullSign, ghFullAttest],
  "container-lifecycle-nix": [ghClnBuild, ghClnScan, ghClnDeploy, ghClnSign, ghClnAttest],
  "full-nix": [
    ghFnBuildAmd64, ghFnBuildArm64,
    ghFnScanAmd64, ghFnScanArm64,
    ghFnDeployAmd64, ghFnDeployArm64,
    ghFnManifest,
    ghFnSignAmd64, ghFnSignArm64,
    ghFnAttestAmd64, ghFnAttestArm64,
  ],
};

await ExportCIComponentsGitHub(templatesGitHub, fileHeader, {
  "container-lifecycle": {
    image_suffix: { description: "Suffix for the image name when building multiple images" as const, default: "" as const },
  },
  full: {
    image_suffix: { description: "Suffix for the image name when building multiple images" as const, default: "" as const },
    devguard_artifact_name: { description: "Name of the artifact you are building (leave empty when building a single artifact)" as const, default: "" as const },
  },
  "container-lifecycle-nix": {
    image_suffix: { description: "Suffix for the image name when building multiple images" as const, default: "" as const },
  },
  "full-nix": {
    nix_target_amd64: { description: "Nix flake build target for amd64 (e.g. devguard-0-amd64)" as const },
    nix_target_arm64: { description: "Nix flake build target for arm64 (e.g. devguard-0-arm64)" as const },
    runner_amd64: { description: "GitHub Actions runner label for the amd64 build" as const, default: "ubuntu-latest" as const },
    runner_arm64: { description: "GitHub Actions runner label for the arm64 build" as const, default: "ubuntu-24.04-arm" as const },
    artifact_name_suffix: { description: "Suffix appended to artifact names to avoid conflicts when building multiple images" as const, default: "" as const },
  },
});

// console.log("Finished");
