on:
  workflow_call:
    inputs:
      asset-name:
        description: 'Name of the asset to be scanned'
        type: string
        required: true
      api-url:
        type: string
        required: false
        default: "https://api.devguard.org"
      sbom-artifact-name:
        description: 'Name of the SBOM artifact to be downloaded'
        type: string
        required: false
        default: ''
      sbom-file:
        description: 'Path to the SBOM file to be scanned'
        type: string
        required: true
        default: "sbom.json"
      artifact-name:
        type: string
        required: false
        default: 'source'
        description: "The name of the artifact you are building. This is useful when a single pipeline builds more than a single artifact like a container with a shell inside and one without. If you build a single artifact - leave it empty."
      web-ui:
        type: string
        required: false
        default: "https://app.devguard.org"
        description: "The URL of the DevGuard Web UI. This is used to link the results in the DevGuard Web UI."
      fail-on-risk:
        type: string
        required: false
        default: "critical"
        description: "Fail the workflow if a dependency with this risk level or higher is found. Valid values are: none, low, medium, high, critical."
      fail-on-cvss:
        type: string
        required: false
        default: "critical"
        description: "Fail the workflow if a dependency with this CVSS score or higher is found. Valid values are: none, low, medium, high, critical."

    secrets:
      devguard-token:
        description: 'DevGuard API token'
        required: true
    
jobs:
  dependency-risk-identification:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      with:
        submodules: recursive
        fetch-depth: 0
        persist-credentials: true # we need the credentials to be able to use the devguard-scanner in private repositories
      uses: actions/checkout@v4 # Check out the repository content to the runner
      
    - name: Download SBOM artifact
      uses: actions/download-artifact@v4
      with:
        name: ${{ inputs.sbom-artifact-name }}
      if: ${{ inputs.sbom-artifact-name != '' }}

    - name: DevGuard Dependency Risk Identification
      uses: docker://ghcr.io/l3montree-dev/devguard/scanner:main
      with:
        args: devguard-scanner sbom ${{ inputs.sbom-file }} --assetName=${{ inputs.asset-name }}  --apiUrl=${{ inputs.api-url }} --token="${{ secrets.devguard-token }}" --defaultRef=${{ github.event.repository.default_branch }} --isTag=${{ github.ref_type == 'tag' }} --ref=${{ github.ref_name }} --artifactName=${{ inputs.artifact-name }} --webUI=${{ inputs.web-ui }} --failOnRisk=${{ inputs.fail-on-risk }} --failOnCVSS=${{ inputs.fail-on-cvss }}